#!/usr/bin/env python3
"""Generate the exact double-double constant tables baked into
`crates/sundials_core/src/sundials_libm.rs`.

Every number this script prints is a *derived* constant: it is the correctly
rounded IEEE-754 binary64 pair (hi, lo) representing a mathematical value such
as pi/2, atan(k/16) or 1/(2n+1)!.  Nothing here is copied from another
library, and nothing is hand-tuned.

Only the Python standard library is used (``decimal``, ``fractions``), so a
reader can re-run it on a bare Python 3 install and diff the output against
the committed Rust source:

    python3 tools/gen_libm_constants.py > /tmp/regenerated.rs
    # then compare the blocks against crates/sundials_core/src/sundials_libm.rs

The working precision (``PREC`` decimal digits) is far above the ~32 decimal
digits a double-double pair can hold, so the last emitted bit is correct.
"""

from decimal import Decimal, getcontext
from fractions import Fraction
import struct

PREC = 120
getcontext().prec = PREC


# --------------------------------------------------------------------------
# high-precision helpers, implemented from series so that no third-party
# arbitrary-precision package is required
# --------------------------------------------------------------------------
def dec_atan(x: Decimal) -> Decimal:
    """atan(x) for |x| <= 1 by the alternating Taylor series.

    Convergence is slow near |x| = 1, so callers use the argument-halving
    identity atan(x) = 2*atan(x / (1 + sqrt(1 + x*x))) first.
    """
    # argument halving until |x| < 0.05 -> at most ~40 terms below
    halvings = 0
    while abs(x) > Decimal("0.05"):
        x = x / (1 + (1 + x * x).sqrt())
        halvings += 1
    term = x
    total = x
    x2 = x * x
    n = 1
    while True:
        term = -term * x2
        contrib = term / (2 * n + 1)
        if contrib == 0:
            break
        total += contrib
        if abs(contrib) < Decimal(10) ** (-(PREC + 10)):
            break
        n += 1
    return total * (2**halvings)


def dec_pi() -> Decimal:
    """pi via Machin's formula: pi/4 = 4*atan(1/5) - atan(1/239)."""
    return 4 * (4 * dec_atan(Decimal(1) / 5) - dec_atan(Decimal(1) / 239))


PI = dec_pi()


# --------------------------------------------------------------------------
# exact conversion of a Decimal to a chain of binary64 values
# --------------------------------------------------------------------------
def bits(x: float) -> int:
    return struct.unpack("<Q", struct.pack("<d", x))[0]


def to_double(value: Fraction) -> float:
    """Correctly rounded (round-half-to-even) binary64 nearest to `value`."""
    return float(value.numerator / value.denominator) if False else _round_frac(value)


def _round_frac(v: Fraction) -> float:
    # Fraction -> float in CPython is already correctly rounded.
    return float(v)


def dec_to_fraction(d: Decimal) -> Fraction:
    sign, digits, exp = d.as_tuple()
    n = int("".join(map(str, digits)))
    if sign:
        n = -n
    return Fraction(n, 1) * Fraction(10) ** exp


def split(value, n):
    """Split a Fraction into `n` binary64 values whose exact sum is nearest it."""
    if isinstance(value, Decimal):
        value = dec_to_fraction(value)
    out = []
    rest = value
    for _ in range(n):
        d = _round_frac(rest)
        out.append(d)
        rest = rest - Fraction(d)
    return out


def emit_pair(name, value, comment):
    hi, lo = split(value, 2)
    print(f"/// {comment}")
    print(f"const {name}: (f64, f64) = (")
    print(f"    f64::from_bits(0x{bits(hi):016x}), // {hi!r}")
    print(f"    f64::from_bits(0x{bits(lo):016x}), // {lo!r}")
    print(");")
    print()


def emit_triple(name, value, comment):
    a, b, c = split(value, 3)
    print(f"/// {comment}")
    print(f"const {name}: (f64, f64, f64) = (")
    for v in (a, b, c):
        print(f"    f64::from_bits(0x{bits(v):016x}), // {v!r}")
    print(");")
    print()


def emit_pair_table(name, values, comment):
    print(f"/// {comment}")
    print(f"const {name}: [(f64, f64); {len(values)}] = [")
    for v in values:
        hi, lo = split(v, 2)
        print(f"    (f64::from_bits(0x{bits(hi):016x}), f64::from_bits(0x{bits(lo):016x})),")
    print("];")
    print()


# --------------------------------------------------------------------------
# emit
# --------------------------------------------------------------------------
def main():
    print("// ==== generated by tools/gen_libm_constants.py -- do not hand-edit ====")
    print()

    emit_triple("PI_OVER_2", PI / 2, "pi/2 as an exact triple-double sum.")
    emit_pair("PI_DD", PI, "pi as an exact double-double sum.")
    emit_pair("PI_OVER_4_DD", PI / 4, "pi/4 as an exact double-double sum.")
    emit_pair("LN2_DD", Decimal(2).ln(), "ln(2) as an exact double-double sum.")

    # sin: sum_{n>=0} (-1)^n z^n / (2n+1)!   with z = r*r
    sin_c = []
    f = Fraction(1)
    for n in range(0, 15):
        # 1/(2n+1)! with sign
        val = Fraction((-1) ** n, 1) / Fraction(factorial(2 * n + 1))
        sin_c.append(val)
    emit_pair_table(
        "SIN_COEF", sin_c, "(-1)^n / (2n+1)! -- Taylor coefficients of sin(r)/r in r^2."
    )

    cos_c = []
    for n in range(0, 15):
        val = Fraction((-1) ** n, 1) / Fraction(factorial(2 * n))
        cos_c.append(val)
    emit_pair_table(
        "COS_COEF", cos_c, "(-1)^n / (2n)! -- Taylor coefficients of cos(r) in r^2."
    )

    # atan: sum_{n>=0} (-1)^n t^(2n+1) / (2n+1)
    atan_c = [Fraction((-1) ** n, 2 * n + 1) for n in range(0, 12)]
    emit_pair_table(
        "ATAN_COEF", atan_c, "(-1)^n / (2n+1) -- Taylor coefficients of atan(t)/t in t^2."
    )

    # atan(k/16) for k = 0..16, the argument-reduction anchor points
    atan_tab = [dec_atan(Decimal(k) / 16) for k in range(0, 17)]
    emit_pair_table("ATAN_TAB", atan_tab, "atan(k/16) for k = 0 ..= 16.")

    # 1/n! for n = 0..24 -- exp(r) on |r| <= ln2/2 needs 24 terms for 2^-107
    emit_pair_table(
        "INV_FACT",
        [Fraction(1, factorial(n)) for n in range(0, 25)],
        "1/n! -- Taylor coefficients of exp(r).",
    )

    # 1/(2n+1) -- atanh(z) = z + z^3/3 + ..., used by the double-double log
    emit_pair_table(
        "ATANH_COEF",
        [Fraction(1, 2 * n + 1) for n in range(0, 10)],
        "1/(2n+1) -- Taylor coefficients of atanh(z)/z in z^2.",
    )

    # log(1 + j/64) for j = 0..64 -- the double-double log anchor points
    emit_pair_table(
        "LOG_TAB_DD",
        [(Decimal(1) + Decimal(j) / 64).ln() for j in range(0, 65)],
        "log(1 + j/64) for j = 0 ..= 64.",
    )

    # 2/pi as a stream of 64-bit words, for Payne-Hanek reduction.
    # TWO_OVER_PI[k] holds bits [64k, 64k+64) of the fractional expansion,
    # i.e. 2/pi = sum_k TWO_OVER_PI[k] * 2^(-64*(k+1)).
    two_over_pi = dec_to_fraction(2 / PI)
    words = []
    rest = two_over_pi
    # 2/pi = 0.63... so the integer part is 0
    assert rest < 1
    for _ in range(24):
        rest = rest * (1 << 64)
        w = int(rest)
        words.append(w)
        rest -= w
    print("/// Bits of 2/pi for Payne-Hanek argument reduction:")
    print("/// `2/pi == sum_k TWO_OVER_PI[k] * 2^(-64*(k+1))`.")
    print(f"const TWO_OVER_PI: [u64; {len(words)}] = [")
    for w in words:
        print(f"    0x{w:016x},")
    print("];")
    print()


def factorial(n):
    r = 1
    for i in range(2, n + 1):
        r *= i
    return r


if __name__ == "__main__":
    main()
