#!/usr/bin/env bash
# glibc_sweep.sh — measure, rather than argue, that this port's platform
# claim covers the Debian, Arch and Fedora families.
#
# README.md § "Distribution coverage" reasons that the claim carries
# because those distributions all ship glibc, so the libm behind `f64`'s
# transcendental methods is the same implementation everywhere. That is a
# testable statement: build tools/libm_probe.c in each distribution and
# compare its per-function hashes. Identical hashes mean the two hosts
# cannot disagree about any of those results, so a verification gate
# established on one transfers to the other.
#
# Alpine (musl) is included deliberately as the negative control — the
# distribution the port does NOT claim. Seeing exactly which functions
# differ there is what makes "musl is out of scope" an evidence-based
# statement rather than caution.
#
#   tools/glibc_sweep.sh [image ...]
#
# Requires docker. Each image gets a C compiler installed inside the
# container; nothing is installed on the host. Writes
# logs/glibc-sweep.txt.
set -u
cd "$(dirname "$0")/.."
WS_ROOT="$PWD"
LOGS="$WS_ROOT/logs"
OUT="$LOGS/glibc-sweep.txt"
mkdir -p "$LOGS"

IMAGES=("$@")
if [ ${#IMAGES[@]} -eq 0 ]; then
  IMAGES=(debian:12 debian:13 fedora:41 archlinux:latest alpine:3.20)
fi

# One install line per distribution family, quiet, no host side effects.
installer() {
  case "$1" in
    debian*|ubuntu*) echo 'export DEBIAN_FRONTEND=noninteractive; apt-get -qq update >/dev/null 2>&1 && apt-get -qq install -y gcc >/dev/null 2>&1' ;;
    fedora*)         echo 'dnf -y -q install gcc >/dev/null 2>&1' ;;
    archlinux*)      echo 'pacman -Sy --noconfirm --quiet gcc >/dev/null 2>&1' ;;
    alpine*)         echo 'apk add --quiet gcc musl-dev >/dev/null 2>&1' ;;
    *)               echo 'true' ;;
  esac
}

run_one() {
  local image="$1"
  docker run --rm -v "$WS_ROOT/tools:/t:ro" "$image" sh -c "
    $(installer "$image")
    command -v cc >/dev/null 2>&1 || ln -sf \"\$(command -v gcc)\" /usr/local/bin/cc 2>/dev/null
    cc -O2 -o /tmp/libm_probe /t/libm_probe.c -lm 2>/dev/null || { echo 'BUILD-FAILED'; exit 1; }
    if ldd --version >/dev/null 2>&1; then ldd --version | head -1; else echo 'libc: musl (no ldd --version)'; fi
    /tmp/libm_probe
  " 2>&1
}

{
  echo "# libm fingerprints across distributions"
  echo "# generated by tools/glibc_sweep.sh; each hash is FNV-1a over the"
  echo "# result bit patterns of 1,000,000 deterministic inputs."
  echo
  echo "=== host (the machine every other claim in this repo was measured on) ==="
  (ldd --version | head -1) 2>/dev/null
  cc -O2 -o "$LOGS/libm_probe" "$WS_ROOT/tools/libm_probe.c" -lm && "$LOGS/libm_probe"
  echo
  for image in "${IMAGES[@]}"; do
    echo "=== $image ==="
    run_one "$image"
    echo
  done
} | tee "$OUT"

echo
echo "wrote $OUT"
