//! C `printf` `%e` / `%f` / `%g` formatting, byte-exact.
//!
//! Every floating-point value printed anywhere in this workspace goes
//! through these helpers (workspace rule 5). Rust's `{:e}` is never used:
//! its exponent form (`1.5e2`) differs from C (`1.500000e+02`).
//!
//! The unit tests assert against 1500+ vectors generated by the system C
//! library's `printf` (`sundials_utils_cvec.txt`) — generated once on
//! macOS / Apple Silicon (arm64) against Apple's libc, then committed and
//! pulled in with `include_str!`. Because the expected strings are frozen
//! data rather than a live `printf` call, this is one of the few pieces of
//! verification evidence in the project that *is* portable: the test passes
//! unchanged on other targets, and a failure there would mean these helpers
//! diverged, not that the host's `printf` did.

/// C `printf("%.*e", prec, x)`.
pub fn fmt_e(x: f64, prec: usize) -> String {
    if x.is_nan() {
        return "nan".to_string();
    }
    if x.is_infinite() {
        return if x < 0.0 { "-inf" } else { "inf" }.to_string();
    }
    let s = format!("{:.*e}", prec, x);
    let epos = s.rfind('e').expect("float e-format always has an exponent");
    let mant = &s[..epos];
    let exp = &s[epos + 1..];
    let (sign, digits) = match exp.strip_prefix('-') {
        Some(d) => ('-', d),
        None => ('+', exp),
    };
    format!("{mant}e{sign}{digits:0>2}")
}

/// C `printf("%.*f", prec, x)`.
pub fn fmt_f(x: f64, prec: usize) -> String {
    if x.is_nan() {
        return "nan".to_string();
    }
    if x.is_infinite() {
        return if x < 0.0 { "-inf" } else { "inf" }.to_string();
    }
    format!("{:.*}", prec, x)
}

/// C `printf("%.*g", prec, x)`.
pub fn fmt_g(x: f64, prec: usize) -> String {
    if x.is_nan() {
        return "nan".to_string();
    }
    if x.is_infinite() {
        return if x < 0.0 { "-inf" } else { "inf" }.to_string();
    }
    let p = if prec == 0 { 1 } else { prec };
    if x == 0.0 {
        return if x.is_sign_negative() { "-0" } else { "0" }.to_string();
    }
    // C99: X = the exponent of the %e conversion at precision P-1 (i.e.
    // after rounding); style e iff X < -4 or X >= P, else style f with
    // precision P-1-X; trailing zeros (and a bare '.') are removed.
    let es = format!("{:.*e}", p - 1, x);
    let epos = es.rfind('e').expect("float e-format always has an exponent");
    let e10: i32 = es[epos + 1..].parse().expect("exponent is an integer");
    if e10 < -4 || e10 >= p as i32 {
        let mant = strip_trailing_zeros(&es[..epos]);
        let exp = &es[epos + 1..];
        let (sign, digits) = match exp.strip_prefix('-') {
            Some(d) => ('-', d),
            None => ('+', exp),
        };
        format!("{mant}e{sign}{digits:0>2}")
    } else {
        let fprec = (p as i32 - 1 - e10) as usize;
        strip_trailing_zeros(&format!("{:.*}", fprec, x)).to_string()
    }
}

fn strip_trailing_zeros(s: &str) -> &str {
    if s.contains('.') {
        let s = s.trim_end_matches('0');
        s.strip_suffix('.').unwrap_or(s)
    } else {
        s
    }
}

/// C `printf("%*.*e", width, prec, x)` (right-justified, space-padded).
pub fn fmt_ew(x: f64, width: usize, prec: usize) -> String {
    format!("{:>width$}", fmt_e(x, prec))
}

/// C `printf("%*.*f", width, prec, x)`.
pub fn fmt_fw(x: f64, width: usize, prec: usize) -> String {
    format!("{:>width$}", fmt_f(x, prec))
}

/// C `printf("%*.*g", width, prec, x)`.
pub fn fmt_gw(x: f64, width: usize, prec: usize) -> String {
    format!("{:>width$}", fmt_g(x, prec))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Same values, same order, as the generator that produced
    /// `sundials_utils_cvec.txt` (system C printf ground truth).
    const VALS: [f64; 41] = [
        0.0,
        -0.0,
        1.0,
        -1.5,
        2.5,
        0.5,
        0.1,
        1.0 / 3.0,
        9.999999999e-5,
        1.5e-300,
        1234567.891,
        6.02214076e23,
        1e100,
        3.9e-105,
        5e-324,
        2.2250738585072014e-308, // DBL_MIN
        1.7976931348623157e308,  // DBL_MAX
        9.999999e99,
        100000.0,
        1000000.0,
        1e-4,
        1e-5,
        120.0,
        0.000123456,
        999999.5,
        1234.5,
        123456789.0,
        -987.654321,
        42.0,
        0.25,
        1.0e-9,
        7.389056098930650,
        2.718281828459045,
        3.141592653589793,
        1.7e-8,
        98765.4321e-12,
        5.5,
        -5.5,
        6.5,
        0.0625,
        1048576.0,
    ];

    #[test]
    fn matches_c_printf_vectors() {
        let data = include_str!("sundials_utils_cvec.txt");
        let mut checked = 0usize;
        for line in data.lines() {
            let mut it = line.splitn(4, '|');
            let kind = it.next().expect("kind field");
            let idx = it.next().expect("idx field");
            let prec: usize = it.next().expect("prec field").parse().expect("prec");
            let expected = it.next().expect("expected field");
            let (x, label): (f64, String) = match idx {
                "inf" => (f64::INFINITY, "inf".to_string()),
                "ninf" => (f64::NEG_INFINITY, "ninf".to_string()),
                "nan" => (f64::NAN, "nan".to_string()),
                n => {
                    let i: usize = n.parse().expect("value index");
                    (VALS[i], format!("VALS[{i}]"))
                }
            };
            let got = match kind {
                "e" => fmt_e(x, prec),
                "f" => fmt_f(x, prec),
                "g" => fmt_g(x, prec),
                other => panic!("unknown kind {other}"),
            };
            assert_eq!(got, expected, "fmt_{kind}({label}={x:?}, {prec})");
            checked += 1;
        }
        assert_eq!(checked, 1565, "all C vectors exercised");
    }

    #[test]
    fn c_atoi_semantics() {
        assert_eq!(atoi("3abc"), 3);
        assert_eq!(atoi("  -42xyz"), -42);
        assert_eq!(atoi("abc"), 0);
        assert_eq!(atoi(""), 0);
        assert_eq!(atoi("+7"), 7);
        assert_eq!(atol("123456789012"), 123456789012i64);
        assert_eq!(atol("- 5"), 0); /* sign must abut digits, as in C */
    }

    #[test]
    fn width_helpers_right_justify() {
        assert_eq!(fmt_ew(1.5, 14, 6), "  1.500000e+00");
        assert_eq!(fmt_fw(3.14159265, 10, 4), "    3.1416");
        assert_eq!(fmt_gw(100000.0, 8, 6), "  100000");
        // width smaller than the output never truncates (C semantics)
        assert_eq!(fmt_ew(1.5, 3, 6), "1.500000e+00");
    }
}

/// C `SUN_FORMAT_E` = `"% .15e"` (space flag: non-negatives get a space).
pub fn sun_format_e(x: f64) -> String {
    let s = fmt_e(x, 15);
    if s.starts_with('-') {
        s
    } else {
        format!(" {s}")
    }
}

/// C `SUN_FORMAT_G` = `"%.15g"`.
pub fn sun_format_g(x: f64) -> String {
    fmt_g(x, 15)
}

/// C `SUN_FORMAT_SG` = `"%+.15g"`.
pub fn sun_format_sg(x: f64) -> String {
    let s = fmt_g(x, 15);
    if s.starts_with('-') {
        s
    } else {
        format!("+{s}")
    }
}

/* ----------------------------------------------------------------------
 * Port of `src/sundials/sundials_utils.h` (common utility helpers) and
 * the C `FILE*` model used across the workspace.
 * -------------------------------------------------------------------- */

use std::cell::RefCell;
use std::io::Write;
use std::rc::Rc;

use crate::sundials_types::{sunrealtype, SUNOutputFormat};

/// Rust stand-in for C `FILE*`. `Null` is a NULL `FILE*`; `Stdout`/`Stderr`
/// are the C standard streams; `File` is an `fopen`ed handle (`Rc` clone =
/// C pointer copy, so pointer equality is `Rc::ptr_eq`).
#[derive(Clone, Default)]
pub enum SUNFile {
    #[default]
    Null,
    Stdout,
    Stderr,
    File(Rc<RefCell<std::fs::File>>),
}

impl SUNFile {
    /// C `fopen(fname, mode)` (modes used in this workspace: "w", "w+", "a").
    pub fn fopen(fname: &str, mode: &str) -> SUNFile {
        let mut opts = std::fs::OpenOptions::new();
        match mode {
            "r" => {
                opts.read(true);
            }
            "a" | "a+" => {
                opts.append(true).create(true).read(mode == "a+");
            }
            _ => {
                /* "w" / "w+" */
                opts.write(true).create(true).truncate(true).read(mode == "w+");
            }
        }
        match opts.open(fname) {
            Ok(f) => SUNFile::File(Rc::new(RefCell::new(f))),
            Err(_) => SUNFile::Null,
        }
    }

    pub fn is_null(&self) -> bool {
        matches!(self, SUNFile::Null)
    }

    /// C `fp == stdout` / `fp == stderr` / pointer comparison.
    pub fn ptr_eq(&self, other: &SUNFile) -> bool {
        match (self, other) {
            (SUNFile::Null, SUNFile::Null) => true,
            (SUNFile::Stdout, SUNFile::Stdout) => true,
            (SUNFile::Stderr, SUNFile::Stderr) => true,
            (SUNFile::File(a), SUNFile::File(b)) => Rc::ptr_eq(a, b),
            _ => false,
        }
    }

    /// C `fprintf(fp, "%s", s)`. Writing to a NULL stream is a no-op here
    /// (C would crash; no caller does this on a valid path).
    pub fn write_str(&self, s: &str) {
        match self {
            SUNFile::Null => {}
            SUNFile::Stdout => {
                let mut out = std::io::stdout();
                let _ = out.write_all(s.as_bytes());
            }
            SUNFile::Stderr => {
                let mut err = std::io::stderr();
                let _ = err.write_all(s.as_bytes());
            }
            SUNFile::File(f) => {
                let _ = f.borrow_mut().write_all(s.as_bytes());
            }
        }
    }

    /// C `fflush(fp)`.
    pub fn fflush(&self) {
        match self {
            SUNFile::Null => {}
            SUNFile::Stdout => {
                let _ = std::io::stdout().flush();
            }
            SUNFile::Stderr => {
                let _ = std::io::stderr().flush();
            }
            SUNFile::File(f) => {
                let _ = f.borrow_mut().flush();
            }
        }
    }
}

/// Width of name field in `sunfprintf_<type>` for aligning table output.
pub const SUN_TABLE_WIDTH: usize = 29;

pub fn sunIsNullOrEmpty(str_: Option<&str>) -> bool {
    match str_ {
        None => true,
        Some(s) => s.is_empty(),
    }
}

pub fn sunSignedToString(val: i64) -> String {
    format!("{val}")
}

pub fn sunCombineFileAndLine(line: i32, file: &str) -> String {
    format!("{file}:{line}")
}

/// C `sunCompensatedSum` (Kahan step; `volatile` in C only inhibits
/// contraction/reassociation, which Rust never performs).
pub fn sunCompensatedSum(
    base: sunrealtype,
    inc: sunrealtype,
    sum: &mut sunrealtype,
    error: &mut sunrealtype,
) {
    let err = *error;
    let tmp1 = inc - err;
    let tmp2 = base + tmp1;
    *error = (tmp2 - base) - tmp1;
    *sum = tmp2;
}

/// C `sunfprintf_real`: `"%-29s = %.15g\n"` (table) or `"%s,% .15e"` (CSV).
pub fn sunfprintf_real(
    fp: &SUNFile,
    fmt: SUNOutputFormat,
    start: bool,
    name: &str,
    value: sunrealtype,
) {
    if fmt == SUNOutputFormat::SUN_OUTPUTFORMAT_TABLE {
        fp.write_str(&format!(
            "{:<width$} = {}\n",
            name,
            sun_format_g(value),
            width = SUN_TABLE_WIDTH
        ));
    } else {
        if !start {
            fp.write_str(",");
        }
        fp.write_str(&format!("{},{}", name, sun_format_e(value)));
    }
}

/// C `sunfprintf_long`.
pub fn sunfprintf_long(fp: &SUNFile, fmt: SUNOutputFormat, start: bool, name: &str, value: i64) {
    if fmt == SUNOutputFormat::SUN_OUTPUTFORMAT_TABLE {
        fp.write_str(&format!(
            "{:<width$} = {}\n",
            name,
            value,
            width = SUN_TABLE_WIDTH
        ));
    } else {
        if !start {
            fp.write_str(",");
        }
        fp.write_str(&format!("{name},{value}"));
    }
}

/// C `sunfprintf_long_array`.
pub fn sunfprintf_long_array(
    fp: &SUNFile,
    fmt: SUNOutputFormat,
    start: bool,
    name: &str,
    value: &[i64],
) {
    if value.is_empty() {
        return;
    }
    if fmt == SUNOutputFormat::SUN_OUTPUTFORMAT_TABLE {
        fp.write_str(&format!(
            "{:<width$} = {}",
            name,
            value[0],
            width = SUN_TABLE_WIDTH
        ));
        for v in &value[1..] {
            fp.write_str(&format!(", {v}"));
        }
        fp.write_str("\n");
    } else {
        if !start {
            fp.write_str(",");
        }
        for (i, v) in value.iter().enumerate() {
            fp.write_str(&format!("{name} {i},{v}"));
        }
    }
}

/// C `atoi(s)`: skip leading whitespace, optional sign, then the longest
/// digit prefix; 0 if no digits. Trailing junk is ignored (unlike Rust's
/// strict `parse`), matching libc for tokens like "3abc".
pub fn atoi(s: &str) -> i32 {
    atol(s) as i32
}

/// C `atol(s)` (see [`atoi`]). Leading-whitespace skip matches C-locale
/// `isspace` (ASCII only), not Unicode.
pub fn atol(s: &str) -> i64 {
    let t = s.trim_start_matches([' ', '\t', '\n', '\x0b', '\x0c', '\r']);
    let b = t.as_bytes();
    let mut i = 0usize;
    let mut neg = false;
    if i < b.len() && (b[i] == b'+' || b[i] == b'-') {
        neg = b[i] == b'-';
        i += 1;
    }
    let start = i;
    let mut val: i64 = 0;
    while i < b.len() && b[i].is_ascii_digit() {
        val = val.wrapping_mul(10).wrapping_add((b[i] - b'0') as i64);
        i += 1;
    }
    if i == start {
        return 0;
    }
    if neg {
        -val
    } else {
        val
    }
}
