//! Pure-Rust elementary functions — the whole host-libm surface this port
//! touches, reimplemented so that **no numerical result depends on the C
//! library the binary happens to link against.**
//!
//! # Why this module exists
//!
//! Rust's `f64::sin`, `f64::cos`, `f64::exp`, `f64::ln`, … are documented as
//! having *unspecified precision*: they forward to the host libm. That makes
//! the printed output of an adaptive integrator a function of the host's
//! glibc **version**, not just of the algorithm — a one-ulp difference in
//! `sinh` forks the step-size trajectory. The sibling
//! `SUNDIALS_7_8_Rust_port_for_Linux` repository measured exactly that: three
//! ARKODE LSRK variants stop reproducing on glibc 2.44 because 2.44 changed
//! `sinh`, `cosh` and `acosh`.
//!
//! Routing every call through this module removes the host libm from the
//! numerical path entirely. The only remaining `f64` methods used are
//! `sqrt`, `mul_add`, `abs`, `ceil`, `round` and `copysign`, all of which
//! IEEE-754 specifies exactly and every Rust target implements identically.
//!
//! # What is implemented, and how faithful each one is
//!
//! Two different fidelity targets are in play, and the distinction is the
//! whole story of this module:
//!
//! | function | algorithm | relationship to glibc ≥ 2.28 on x86-64 |
//! |---|---|---|
//! | [`exp`], [`log`], [`pow`] | ARM optimized-routines (MIT), via musl | *the same source glibc ships* — expected and measured bit-identical |
//! | [`expm1`], [`log1p`], [`sinh`], [`cosh`], [`acosh`] | fdlibm / SunPro, via musl | the same lineage glibc ships — measured bit-identical |
//! | [`sin`], [`cos`], [`atan`], [`asin`], [`acos`] | double-double, written here | **correctly rounded**; glibc uses the LGPL IBM Accurate Mathematical Library, which is *not* correctly rounded (~0.51 ulp), so the two disagree on the last bit for a small measured fraction of inputs |
//!
//! The last row is a deliberate, licence-driven choice: glibc's `sin`/`cos`/
//! `atan`/`asin`/`acos` are LGPL-2.1 and cannot be copied into this
//! BSD-3-Clause tree, and no permissively licensed *bit-identical* equivalent
//! exists. Rather than ship a less accurate fdlibm clone that would disagree
//! with glibc *more* often, this module computes those five to ~2^-100
//! internal accuracy and rounds once — which is both the most accurate
//! option available and the closest achievable match to glibc.
//! `tools/libm_differential.sh` measures the residual disagreement rate
//! rather than asserting anything about it; see `LIBM.md`.
//!
//! # Provenance and licence
//!
//! * [`exp`], [`log`] and [`pow`] are translations of the ARM
//!   optimized-routines double-precision kernels, taken via musl's
//!   `src/math/{exp,log,pow}.c` and `{exp,log,pow}_data.c` — MIT,
//!   Copyright © 2018 Arm Limited. glibc ships the same algorithm as
//!   `sysdeps/ieee754/dbl-64/e_{exp,log,pow}.c`.
//! * [`expm1`], [`log1p`], [`sinh`], [`cosh`] and [`acosh`] are translations
//!   of the FreeBSD msun / SunPro fdlibm kernels, taken via musl's
//!   `src/math/{expm1,log1p,sinh,cosh,acosh}.c` — Copyright © 1993 Sun
//!   Microsystems, freely redistributable with notice preserved.
//! * The double-double core and the five inverse/forward trigonometric
//!   functions built on it are original to this repository. Their constant
//!   tables are generated by `tools/gen_libm_constants.py` from Taylor
//!   series in Python's stdlib `decimal`, and are reproducible by re-running
//!   that script.
//!
//! See `NOTICE` and `LIBM.md`.

use crate::sundials_math::{
    pow_glibc, EXP_INVLN2N, EXP_NEGLN2HIN, EXP_NEGLN2LON, EXP_POLY, EXP_SHIFT, EXP_TAB,
};

/* =====================================================================
 * Double-double arithmetic
 * =====================================================================
 * Unevaluated sums `hi + lo` with `|lo| <= 0.5 * ulp(hi)`, giving about
 * 106 significant bits. The algorithms are the classical
 * Dekker/Knuth/Bailey ones; `two_prod` uses `f64::mul_add`, which Rust
 * guarantees to be a single fused multiply-add, so the product error term
 * is exact.
 */

/// An unevaluated sum `.0 + .1` carrying ~106 significant bits.
#[derive(Clone, Copy, Debug)]
pub struct Dd(pub f64, pub f64);

impl Dd {
    /// Round the double-double back to the nearest `f64`.
    #[inline]
    pub fn value(self) -> f64 {
        self.0 + self.1
    }
}

/// Knuth's `TwoSum`: exact for any finite `a`, `b`.
#[inline]
fn two_sum(a: f64, b: f64) -> (f64, f64) {
    let s = a + b;
    let bb = s - a;
    let err = (a - (s - bb)) + (b - bb);
    (s, err)
}

/// Dekker's `FastTwoSum`: exact provided `|a| >= |b|`.
#[inline]
fn quick_two_sum(a: f64, b: f64) -> (f64, f64) {
    let s = a + b;
    let err = b - (s - a);
    (s, err)
}

/// Exact product `a * b = p + e`, using one fused multiply-add.
#[inline]
fn two_prod(a: f64, b: f64) -> (f64, f64) {
    let p = a * b;
    let e = a.mul_add(b, -p);
    (p, e)
}

#[inline]
fn dd(hi: f64) -> Dd {
    Dd(hi, 0.0)
}

#[inline]
fn dd_neg(a: Dd) -> Dd {
    Dd(-a.0, -a.1)
}

#[inline]
fn dd_add(a: Dd, b: Dd) -> Dd {
    let (s1, e1) = two_sum(a.0, b.0);
    let (s2, e2) = two_sum(a.1, b.1);
    let (s, e) = quick_two_sum(s1, e1 + s2);
    let (s, e) = quick_two_sum(s, e + e2);
    Dd(s, e)
}

#[inline]
fn dd_sub(a: Dd, b: Dd) -> Dd {
    dd_add(a, dd_neg(b))
}

#[inline]
fn dd_add_d(a: Dd, b: f64) -> Dd {
    let (s, e) = two_sum(a.0, b);
    let (s, e) = quick_two_sum(s, e + a.1);
    Dd(s, e)
}

#[inline]
fn dd_mul(a: Dd, b: Dd) -> Dd {
    let (p, e) = two_prod(a.0, b.0);
    let e = e + (a.0 * b.1 + a.1 * b.0);
    let (s, e) = quick_two_sum(p, e);
    Dd(s, e)
}

#[inline]
fn dd_mul_d(a: Dd, b: f64) -> Dd {
    let (p, e) = two_prod(a.0, b);
    let (s, e) = quick_two_sum(p, e + a.1 * b);
    Dd(s, e)
}

/// Division by Newton refinement; three quotient digits give ~106 bits.
fn dd_div(a: Dd, b: Dd) -> Dd {
    let q1 = a.0 / b.0;
    let r = dd_sub(a, dd_mul_d(b, q1));
    let q2 = r.0 / b.0;
    let r = dd_sub(r, dd_mul_d(b, q2));
    let q3 = r.0 / b.0;
    let (s, e) = quick_two_sum(q1, q2);
    dd_add_d(Dd(s, e), q3)
}

/// Square root by one Newton step on the reciprocal square root.
fn dd_sqrt(a: Dd) -> Dd {
    if a.0 == 0.0 {
        return Dd(0.0, 0.0);
    }
    let x = 1.0 / a.0.sqrt();
    let ax = a.0 * x;
    let (p, e) = two_prod(ax, ax);
    let diff = dd_sub(a, Dd(p, e));
    let e2 = diff.0 * x * 0.5;
    let (s, e) = quick_two_sum(ax, e2);
    Dd(s, e)
}

/// Multiply by an exact power of two (no rounding).
#[inline]
fn dd_scale2(a: Dd, p: f64) -> Dd {
    Dd(a.0 * p, a.1 * p)
}

// ==== generated by tools/gen_libm_constants.py -- do not hand-edit ====

/// pi/2 as an exact triple-double sum.
const PI_OVER_2: (f64, f64, f64) = (
    f64::from_bits(0x3ff921fb54442d18), // 1.5707963267948966
    f64::from_bits(0x3c91a62633145c07), // 6.123233995736766e-17
    f64::from_bits(0xb91f1976b7ed8fbc), // -1.4973849048591698e-33
);

/// pi as an exact double-double sum.
const PI_DD: (f64, f64) = (
    f64::from_bits(0x400921fb54442d18), // 3.141592653589793
    f64::from_bits(0x3ca1a62633145c07), // 1.2246467991473532e-16
);

/// pi/4 as an exact double-double sum.
const PI_OVER_4_DD: (f64, f64) = (
    f64::from_bits(0x3fe921fb54442d18), // 0.7853981633974483
    f64::from_bits(0x3c81a62633145c07), // 3.061616997868383e-17
);

/// ln(2) as an exact double-double sum.
const LN2_DD: (f64, f64) = (
    f64::from_bits(0x3fe62e42fefa39ef), // 0.6931471805599453
    f64::from_bits(0x3c7abc9e3b39803f), // 2.3190468138462996e-17
);

/// (-1)^n / (2n+1)! -- Taylor coefficients of sin(r)/r in r^2.
const SIN_COEF: [(f64, f64); 15] = [
    (f64::from_bits(0x3ff0000000000000), f64::from_bits(0x0000000000000000)),
    (f64::from_bits(0xbfc5555555555555), f64::from_bits(0xbc65555555555555)),
    (f64::from_bits(0x3f81111111111111), f64::from_bits(0x3c01111111111111)),
    (f64::from_bits(0xbf2a01a01a01a01a), f64::from_bits(0xbb6a01a01a01a01a)),
    (f64::from_bits(0x3ec71de3a556c734), f64::from_bits(0xbb6c154f8ddc6c00)),
    (f64::from_bits(0xbe5ae64567f544e4), f64::from_bits(0x3afc062e06d1f209)),
    (f64::from_bits(0x3de6124613a86d09), f64::from_bits(0x3a8f28e0cc748ebe)),
    (f64::from_bits(0xbd6ae7f3e733b81f), f64::from_bits(0xb9e1d8656b0ee8cb)),
    (f64::from_bits(0x3ce952c77030ad4a), f64::from_bits(0x398ac981465ddc6c)),
    (f64::from_bits(0xbc62f49b46814157), f64::from_bits(0xb8f2650f61dbdcb4)),
    (f64::from_bits(0x3bd71b8ef6dcf572), f64::from_bits(0xb87d043ae40c4647)),
    (f64::from_bits(0xbb4761b41316381a), f64::from_bits(0x37d3423c7d91404f)),
    (f64::from_bits(0x3ab3f3ccdd165fa9), f64::from_bits(0xb7458ddadf344487)),
    (f64::from_bits(0xba1d1ab1c2dccea3), f64::from_bits(0xb6a054d0c78aea14)),
    (f64::from_bits(0x398259f98b4358ad), f64::from_bits(0x362eaf8c39dd9bc5)),
];

/// (-1)^n / (2n)! -- Taylor coefficients of cos(r) in r^2.
const COS_COEF: [(f64, f64); 15] = [
    (f64::from_bits(0x3ff0000000000000), f64::from_bits(0x0000000000000000)),
    (f64::from_bits(0xbfe0000000000000), f64::from_bits(0x0000000000000000)),
    (f64::from_bits(0x3fa5555555555555), f64::from_bits(0x3c45555555555555)),
    (f64::from_bits(0xbf56c16c16c16c17), f64::from_bits(0x3bef49f49f49f49f)),
    (f64::from_bits(0x3efa01a01a01a01a), f64::from_bits(0x3b3a01a01a01a01a)),
    (f64::from_bits(0xbe927e4fb7789f5c), f64::from_bits(0xbb3cbbc05b4fa99a)),
    (f64::from_bits(0x3e21eed8eff8d898), f64::from_bits(0xbac2aec959e14c06)),
    (f64::from_bits(0xbda93974a8c07c9d), f64::from_bits(0xba305d6f8a2efd1f)),
    (f64::from_bits(0x3d2ae7f3e733b81f), f64::from_bits(0x39a1d8656b0ee8cb)),
    (f64::from_bits(0xbca6827863b97d97), f64::from_bits(0xb94eec01221a8b0b)),
    (f64::from_bits(0x3c1e542ba4020225), f64::from_bits(0x387ea72b4afe3c2f)),
    (f64::from_bits(0xbb90ce396db7f853), f64::from_bits(0x383aebcdbd20331c)),
    (f64::from_bits(0x3aff2cf01972f578), f64::from_bits(0xb789ada5fcc1ab14)),
    (f64::from_bits(0xba688e85fc6a4e5a), f64::from_bits(0x37071c37ebd16540)),
    (f64::from_bits(0x39d0a18a2635085d), f64::from_bits(0x366b9e2e28e1aa54)),
];

/// (-1)^n / (2n+1) -- Taylor coefficients of atan(t)/t in t^2.
const ATAN_COEF: [(f64, f64); 12] = [
    (f64::from_bits(0x3ff0000000000000), f64::from_bits(0x0000000000000000)),
    (f64::from_bits(0xbfd5555555555555), f64::from_bits(0xbc75555555555555)),
    (f64::from_bits(0x3fc999999999999a), f64::from_bits(0xbc6999999999999a)),
    (f64::from_bits(0xbfc2492492492492), f64::from_bits(0xbc62492492492492)),
    (f64::from_bits(0x3fbc71c71c71c71c), f64::from_bits(0x3c5c71c71c71c71c)),
    (f64::from_bits(0xbfb745d1745d1746), f64::from_bits(0x3c4745d1745d1746)),
    (f64::from_bits(0x3fb3b13b13b13b14), f64::from_bits(0xbc53b13b13b13b14)),
    (f64::from_bits(0xbfb1111111111111), f64::from_bits(0xbc31111111111111)),
    (f64::from_bits(0x3fae1e1e1e1e1e1e), f64::from_bits(0x3c2e1e1e1e1e1e1e)),
    (f64::from_bits(0xbfaaf286bca1af28), f64::from_bits(0xbc4af286bca1af28)),
    (f64::from_bits(0x3fa8618618618618), f64::from_bits(0x3c48618618618618)),
    (f64::from_bits(0xbfa642c8590b2164), f64::from_bits(0xbc3642c8590b2164)),
];

/// atan(k/16) for k = 0 ..= 16.
const ATAN_TAB: [(f64, f64); 17] = [
    (f64::from_bits(0x0000000000000000), f64::from_bits(0x0000000000000000)),
    (f64::from_bits(0x3faff55bb72cfdea), f64::from_bits(0xbc3c934d86d23f1d)),
    (f64::from_bits(0x3fbfd5ba9aac2f6e), f64::from_bits(0xbc4cd37686760c17)),
    (f64::from_bits(0x3fc7b97b4bce5b02), f64::from_bits(0x3c5347b0b4f881ca)),
    (f64::from_bits(0x3fcf5b75f92c80dd), f64::from_bits(0x3c68ab6e3cf7afbd)),
    (f64::from_bits(0x3fd362773707ebcc), f64::from_bits(0xbc6963a544b672d8)),
    (f64::from_bits(0x3fd6f61941e4def1), f64::from_bits(0xbc7c63aae6f6e918)),
    (f64::from_bits(0x3fda64eec3cc23fd), f64::from_bits(0xbc724dec1b50b7ff)),
    (f64::from_bits(0x3fddac670561bb4f), f64::from_bits(0x3c7a2b7f222f65e2)),
    (f64::from_bits(0x3fe0657e94db30d0), f64::from_bits(0xbc7d5b495f6349e6)),
    (f64::from_bits(0x3fe1e00babdefeb4), f64::from_bits(0xbc5928df287a668f)),
    (f64::from_bits(0x3fe345f01cce37bb), f64::from_bits(0x3c81021137c71102)),
    (f64::from_bits(0x3fe4978fa3269ee1), f64::from_bits(0x3c72419a87f2a458)),
    (f64::from_bits(0x3fe5d58987169b18), f64::from_bits(0x3c60028e4bc5e7ca)),
    (f64::from_bits(0x3fe700a7c5784634), f64::from_bits(0xbc78c34d25aadef6)),
    (f64::from_bits(0x3fe819d0b7158a4d), f64::from_bits(0xbc7bf76229d3b917)),
    (f64::from_bits(0x3fe921fb54442d18), f64::from_bits(0x3c81a62633145c07)),
];

/// 1/n! -- Taylor coefficients of exp(r).
const INV_FACT: [(f64, f64); 25] = [
    (f64::from_bits(0x3ff0000000000000), f64::from_bits(0x0000000000000000)),
    (f64::from_bits(0x3ff0000000000000), f64::from_bits(0x0000000000000000)),
    (f64::from_bits(0x3fe0000000000000), f64::from_bits(0x0000000000000000)),
    (f64::from_bits(0x3fc5555555555555), f64::from_bits(0x3c65555555555555)),
    (f64::from_bits(0x3fa5555555555555), f64::from_bits(0x3c45555555555555)),
    (f64::from_bits(0x3f81111111111111), f64::from_bits(0x3c01111111111111)),
    (f64::from_bits(0x3f56c16c16c16c17), f64::from_bits(0xbbef49f49f49f49f)),
    (f64::from_bits(0x3f2a01a01a01a01a), f64::from_bits(0x3b6a01a01a01a01a)),
    (f64::from_bits(0x3efa01a01a01a01a), f64::from_bits(0x3b3a01a01a01a01a)),
    (f64::from_bits(0x3ec71de3a556c734), f64::from_bits(0xbb6c154f8ddc6c00)),
    (f64::from_bits(0x3e927e4fb7789f5c), f64::from_bits(0x3b3cbbc05b4fa99a)),
    (f64::from_bits(0x3e5ae64567f544e4), f64::from_bits(0xbafc062e06d1f209)),
    (f64::from_bits(0x3e21eed8eff8d898), f64::from_bits(0xbac2aec959e14c06)),
    (f64::from_bits(0x3de6124613a86d09), f64::from_bits(0x3a8f28e0cc748ebe)),
    (f64::from_bits(0x3da93974a8c07c9d), f64::from_bits(0x3a305d6f8a2efd1f)),
    (f64::from_bits(0x3d6ae7f3e733b81f), f64::from_bits(0x39e1d8656b0ee8cb)),
    (f64::from_bits(0x3d2ae7f3e733b81f), f64::from_bits(0x39a1d8656b0ee8cb)),
    (f64::from_bits(0x3ce952c77030ad4a), f64::from_bits(0x398ac981465ddc6c)),
    (f64::from_bits(0x3ca6827863b97d97), f64::from_bits(0x394eec01221a8b0b)),
    (f64::from_bits(0x3c62f49b46814157), f64::from_bits(0x38f2650f61dbdcb4)),
    (f64::from_bits(0x3c1e542ba4020225), f64::from_bits(0x387ea72b4afe3c2f)),
    (f64::from_bits(0x3bd71b8ef6dcf572), f64::from_bits(0xb87d043ae40c4647)),
    (f64::from_bits(0x3b90ce396db7f853), f64::from_bits(0xb83aebcdbd20331c)),
    (f64::from_bits(0x3b4761b41316381a), f64::from_bits(0xb7d3423c7d91404f)),
    (f64::from_bits(0x3aff2cf01972f578), f64::from_bits(0xb789ada5fcc1ab14)),
];

/// 1/(2n+1) -- Taylor coefficients of atanh(z)/z in z^2.
const ATANH_COEF: [(f64, f64); 10] = [
    (f64::from_bits(0x3ff0000000000000), f64::from_bits(0x0000000000000000)),
    (f64::from_bits(0x3fd5555555555555), f64::from_bits(0x3c75555555555555)),
    (f64::from_bits(0x3fc999999999999a), f64::from_bits(0xbc6999999999999a)),
    (f64::from_bits(0x3fc2492492492492), f64::from_bits(0x3c62492492492492)),
    (f64::from_bits(0x3fbc71c71c71c71c), f64::from_bits(0x3c5c71c71c71c71c)),
    (f64::from_bits(0x3fb745d1745d1746), f64::from_bits(0xbc4745d1745d1746)),
    (f64::from_bits(0x3fb3b13b13b13b14), f64::from_bits(0xbc53b13b13b13b14)),
    (f64::from_bits(0x3fb1111111111111), f64::from_bits(0x3c31111111111111)),
    (f64::from_bits(0x3fae1e1e1e1e1e1e), f64::from_bits(0x3c2e1e1e1e1e1e1e)),
    (f64::from_bits(0x3faaf286bca1af28), f64::from_bits(0x3c4af286bca1af28)),
];

/// log(1 + j/64) for j = 0 ..= 64.
const LOG_TAB_DD: [(f64, f64); 65] = [
    (f64::from_bits(0x0000000000000000), f64::from_bits(0x0000000000000000)),
    (f64::from_bits(0x3f8fc0a8b0fc03e4), f64::from_bits(0xbc183092c59642a1)),
    (f64::from_bits(0x3f9f829b0e783300), f64::from_bits(0x3c333e3f04f1ef23)),
    (f64::from_bits(0x3fa77458f632dcfc), f64::from_bits(0x3c418d3ca87b9296)),
    (f64::from_bits(0x3faf0a30c01162a6), f64::from_bits(0x3c485f325c5bbacd)),
    (f64::from_bits(0x3fb341d7961bd1d1), f64::from_bits(0xbc5b599f227becbb)),
    (f64::from_bits(0x3fb6f0d28ae56b4c), f64::from_bits(0xbc5906d99184b992)),
    (f64::from_bits(0x3fba926d3a4ad563), f64::from_bits(0x3c5942f48aa70ea9)),
    (f64::from_bits(0x3fbe27076e2af2e6), f64::from_bits(0xbc361578001e0162)),
    (f64::from_bits(0x3fc0d77e7cd08e59), f64::from_bits(0x3c69a5dc5e9030ac)),
    (f64::from_bits(0x3fc29552f81ff523), f64::from_bits(0x3c6301771c407dbf)),
    (f64::from_bits(0x3fc44d2b6ccb7d1e), f64::from_bits(0x3c69f4f6543e1f88)),
    (f64::from_bits(0x3fc5ff3070a793d4), f64::from_bits(0xbc5bc60efafc6f6e)),
    (f64::from_bits(0x3fc7ab890210d909), f64::from_bits(0x3c4be36b2d6a0608)),
    (f64::from_bits(0x3fc9525a9cf456b4), f64::from_bits(0x3c6d904c1d4e2e26)),
    (f64::from_bits(0x3fcaf3c94e80bff3), f64::from_bits(0xbc5398cff3641985)),
    (f64::from_bits(0x3fcc8ff7c79a9a22), f64::from_bits(0xbc64f689f8434012)),
    (f64::from_bits(0x3fce27076e2af2e6), f64::from_bits(0xbc461578001e0162)),
    (f64::from_bits(0x3fcfb9186d5e3e2b), f64::from_bits(0xbc6caaae64f21acb)),
    (f64::from_bits(0x3fd0a324e27390e3), f64::from_bits(0x3c77dcfde8061c03)),
    (f64::from_bits(0x3fd1675cababa60e), f64::from_bits(0x3c2ce63eab883717)),
    (f64::from_bits(0x3fd22941fbcf7966), f64::from_bits(0xbc776f5eb09628af)),
    (f64::from_bits(0x3fd2e8e2bae11d31), f64::from_bits(0xbc78f4cdb95ebdf9)),
    (f64::from_bits(0x3fd3a64c556945ea), f64::from_bits(0xbc6c68651945f97c)),
    (f64::from_bits(0x3fd4618bc21c5ec2), f64::from_bits(0x3c7f42decdeccf1d)),
    (f64::from_bits(0x3fd51aad872df82d), f64::from_bits(0x3c43927ac19f55e3)),
    (f64::from_bits(0x3fd5d1bdbf5809ca), f64::from_bits(0x3c74236383dc7fe1)),
    (f64::from_bits(0x3fd686c81e9b14af), f64::from_bits(0xbc6ddea0f7f58e3d)),
    (f64::from_bits(0x3fd739d7f6bbd007), f64::from_bits(0xbc78c76ceb014b04)),
    (f64::from_bits(0x3fd7eaf83b82afc3), f64::from_bits(0x3c792ce979ed2950)),
    (f64::from_bits(0x3fd89a3386c1425b), f64::from_bits(0xbc729639dfbbf0fb)),
    (f64::from_bits(0x3fd947941c2116fb), f64::from_bits(0xbc716cc8bae0bbe4)),
    (f64::from_bits(0x3fd9f323ecbf984c), f64::from_bits(0xbc4a92e513217f5c)),
    (f64::from_bits(0x3fda9cec9a9a084a), f64::from_bits(0xbc7cadec02b436af)),
    (f64::from_bits(0x3fdb44f77bcc8f63), f64::from_bits(0xbc7cd04495459c78)),
    (f64::from_bits(0x3fdbeb4d9da71b7c), f64::from_bits(0xbc40f3c590a887ca)),
    (f64::from_bits(0x3fdc8ff7c79a9a22), f64::from_bits(0xbc74f689f8434012)),
    (f64::from_bits(0x3fdd32fe7e00ebd5), f64::from_bits(0x3c7877b232fafa37)),
    (f64::from_bits(0x3fddd46a04c1c4a1), f64::from_bits(0xbc70467656d8b892)),
    (f64::from_bits(0x3fde744261d68788), f64::from_bits(0xbc5c825c90c344b9)),
    (f64::from_bits(0x3fdf128f5faf06ed), f64::from_bits(0xbc7328df13bb38c3)),
    (f64::from_bits(0x3fdfaf588f78f31f), f64::from_bits(0xbc6328260d8abca0)),
    (f64::from_bits(0x3fe02552a5a5d0ff), f64::from_bits(0xbc7cb1cb51408c00)),
    (f64::from_bits(0x3fe0723e5c1cdf40), f64::from_bits(0x3c8395e58e2445bb)),
    (f64::from_bits(0x3fe0be72e4252a83), f64::from_bits(0xbc8259da11330801)),
    (f64::from_bits(0x3fe109f39e2d4c97), f64::from_bits(0xbc30e09b27a4373a)),
    (f64::from_bits(0x3fe154c3d2f4d5ea), f64::from_bits(0xbc859c33171a6876)),
    (f64::from_bits(0x3fe19ee6b467c96f), f64::from_bits(0xbc79d1a11443f10c)),
    (f64::from_bits(0x3fe1e85f5e7040d0), f64::from_bits(0x3c7ef62cd2f9f1e3)),
    (f64::from_bits(0x3fe23130d7bebf43), f64::from_bits(0xbc8f48725e374d6e)),
    (f64::from_bits(0x3fe2795e1289b11b), f64::from_bits(0xbc6487c0c246978e)),
    (f64::from_bits(0x3fe2c0e9ed448e8c), f64::from_bits(0xbc81a158f3917586)),
    (f64::from_bits(0x3fe307d7334f10be), f64::from_bits(0x3c6fb590a1f566da)),
    (f64::from_bits(0x3fe34e289d9ce1d3), f64::from_bits(0x3c66eb92d885ce4f)),
    (f64::from_bits(0x3fe393e0d3562a1a), f64::from_bits(0xbc858eef67f2483a)),
    (f64::from_bits(0x3fe3d9026a7156fb), f64::from_bits(0xbc86fef670bd4b62)),
    (f64::from_bits(0x3fe41d8fe84672ae), f64::from_bits(0x3c89192f30bd1806)),
    (f64::from_bits(0x3fe4618bc21c5ec2), f64::from_bits(0x3c8f42decdeccf1d)),
    (f64::from_bits(0x3fe4a4f85db03ebb), f64::from_bits(0x3c313dfa3d3761b6)),
    (f64::from_bits(0x3fe4e7d811b75bb1), f64::from_bits(0xbc88d3d9ea6e9ea9)),
    (f64::from_bits(0x3fe52a2d265bc5ab), f64::from_bits(0xbc61883750ea4d0a)),
    (f64::from_bits(0x3fe56bf9d5b3f399), f64::from_bits(0x3c80471885cd8ff3)),
    (f64::from_bits(0x3fe5ad404c359f2d), f64::from_bits(0xbc435955683f7196)),
    (f64::from_bits(0x3fe5ee02a9241675), f64::from_bits(0x3c8c358257f49082)),
    (f64::from_bits(0x3fe62e42fefa39ef), f64::from_bits(0x3c7abc9e3b39803f)),
];

/// Bits of 2/pi for Payne-Hanek argument reduction:
/// `2/pi == sum_k TWO_OVER_PI[k] * 2^(-64*(k+1))`.
const TWO_OVER_PI: [u64; 24] = [
    0xa2f9836e4e441529,
    0xfc2757d1f534ddc0,
    0xdb6295993c439041,
    0xfe5163abdebbc561,
    0xb7246e3a424dd2e0,
    0x06492eea09d1921c,
    0xfe2bef8e95f21bde,
    0x85b57daf93a86fb9,
    0x7cc21246101dc689,
    0xbc58b0d10af2c2d9,
    0x61dc0ca3eb0ce5e6,
    0x669c22aea2e516f7,
    0xfe24b5e3ad86c4ae,
    0xac8badc6297f2904,
    0xd9a5b5876ea4568f,
    0x2876b5f3ecfb5a33,
    0x15e322d541e2315e,
    0xa3ebf45f537a7347,
    0x2c62e69192b80cc2,
    0xaaece5416eed724e,
    0x9dc4296e3823277d,
    0x550c25135bf11477,
    0xea745c504c438629,
    0xe5acb7eff56a2027,
];

// ==== end generated block ====

/* =====================================================================
 * exp — ARM optimized-routines, via musl src/math/exp.c (MIT)
 * ===================================================================== */

/// C `specialcase` from musl's `exp.c`: results that overflow or underflow
/// the plain `scale*(1+tmp)` evaluation.
fn exp_specialcase(tmp: f64, sbits: u64, ki: u64) -> f64 {
    if (ki & 0x80000000) == 0 {
        /* k > 0, the exponent of scale might have overflowed by <= 460. */
        let sbits = sbits.wrapping_sub(1009u64 << 52);
        let scale = f64::from_bits(sbits);
        return f64::from_bits(0x7f00000000000000) * scale.mul_add(tmp, scale); /* 0x1p1009 */
    }
    /* k < 0, need special care in the subnormal range. */
    let sbits = sbits.wrapping_add(1022u64 << 52);
    let scale = f64::from_bits(sbits);
    let mut y = scale + scale * tmp;
    if y < 1.0 {
        /* Round y to the right precision before scaling it into the
        subnormal range, to avoid a double rounding. */
        let mut lo = scale - y + scale * tmp;
        let hi = 1.0 + y;
        lo = 1.0 - hi + y + lo;
        y = (hi + lo) - 1.0;
        if y == 0.0 {
            y = 0.0; /* avoid -0.0 with downward rounding */
        }
    }
    f64::from_bits(0x0010000000000000) * y /* 0x1p-1022 */
}

#[inline]
fn top12(x: f64) -> u32 {
    (x.to_bits() >> 52) as u32
}

/// `e^x`. Translation of musl `src/math/exp.c` (ARM optimized-routines,
/// MIT) — the algorithm and tables glibc ≥ 2.28 ships as
/// `sysdeps/ieee754/dbl-64/e_exp.c`. Worst-case error 0.51 ulp.
pub fn exp(x: f64) -> f64 {
    let mut abstop = top12(x) & 0x7ff;
    /* top12(exp2i(-54)) = 0x3c9, top12(512.0) = 0x408, top12(1024.0) = 0x409 */
    if abstop.wrapping_sub(0x3c9) >= 0x408u32.wrapping_sub(0x3c9) {
        if abstop.wrapping_sub(0x3c9) >= 0x80000000 {
            /* Avoid spurious underflow for tiny x. Note: 0 is a common input. */
            return 1.0 + x;
        }
        if abstop >= 0x409 {
            if x.to_bits() == f64::NEG_INFINITY.to_bits() {
                return 0.0;
            }
            if abstop >= 0x7ff {
                return 1.0 + x;
            }
            if x.to_bits() >> 63 != 0 {
                return 0.0; /* __math_uflow(0) */
            } else {
                return f64::INFINITY; /* __math_oflow(0) */
            }
        }
        /* Large x is special cased below. */
        abstop = 0;
    }

    /* exp(x) = 2^(k/N) * exp(r), with exp(r) in [2^(-1/2N),2^(1/2N)]. */
    let z = f64::from_bits(EXP_INVLN2N) * x;
    let shift = f64::from_bits(EXP_SHIFT);
    let mut kd = z + shift;
    let ki = kd.to_bits();
    kd -= shift;
    let r = x + kd * f64::from_bits(EXP_NEGLN2HIN) + kd * f64::from_bits(EXP_NEGLN2LON);
    /* 2^(k/N) ~= scale * (1 + tail). */
    let idx = (2 * (ki % 128)) as usize; /* EXP_TABLE_BITS = 7 */
    let top = ki << (52 - 7);
    let tail = f64::from_bits(EXP_TAB[idx]);
    let sbits = EXP_TAB[idx + 1].wrapping_add(top);
    let r2 = r * r;
    let c2 = f64::from_bits(EXP_POLY[0]);
    let c3 = f64::from_bits(EXP_POLY[1]);
    let c4 = f64::from_bits(EXP_POLY[2]);
    let c5 = f64::from_bits(EXP_POLY[3]);
    /* glibc's x86-64 `e_exp-fma.c` is built with `-mfma -mavx2
    -ffp-contract=fast`; this is the same contraction map already measured
    bit-exact for `pow` in `sundials_math.rs`. */
    let tmp = (r2 * r2).mul_add(r.mul_add(c5, c4), r2.mul_add(r.mul_add(c3, c2), tail + r));
    if abstop == 0 {
        return exp_specialcase(tmp, sbits, ki);
    }
    let scale = f64::from_bits(sbits);
    scale.mul_add(tmp, scale)
}

/* =====================================================================
 * log — ARM optimized-routines, via musl src/math/log.c (MIT)
 * ===================================================================== */

const LOG_LN2HI: u64 = 0x3fe62e42fefa3800;
const LOG_LN2LO: u64 = 0x3d2ef35793c76730;

const LOG_POLY1: [u64; 11] = [
    0xbfe0000000000000, // -0x1p-1
    0x3fd5555555555577, // 0x1.5555555555577p-2
    0xbfcffffffffffdcb, // -0x1.ffffffffffdcbp-3
    0x3fc999999995dd0c, // 0x1.999999995dd0cp-3
    0xbfc55555556745a7, // -0x1.55555556745a7p-3
    0x3fc24924a344de30, // 0x1.24924a344de3p-3
    0xbfbfffffa4423d65, // -0x1.fffffa4423d65p-4
    0x3fbc7184282ad6ca, // 0x1.c7184282ad6cap-4
    0xbfb999eb43b068ff, // -0x1.999eb43b068ffp-4
    0x3fb78182f7afd085, // 0x1.78182f7afd085p-4
    0xbfb5521375d145cd, // -0x1.5521375d145cdp-4
];

const LOG_POLY: [u64; 5] = [
    0xbfe0000000000001, // -0x1.0000000000001p-1
    0x3fd555555551305b, // 0x1.555555551305bp-2
    0xbfcfffffffeb4590, // -0x1.fffffffeb459p-3
    0x3fc999b324f10111, // 0x1.999b324f10111p-3
    0xbfc55575e506c89f, // -0x1.55575e506c89fp-3
];

/* (invc, logc) */
const LOG_TAB: [(u64, u64); 128] = [
    (0x3ff734f0c3e0de9f, 0xbfd7cc7f79e69000),
    (0x3ff713786a2ce91f, 0xbfd76feec20d0000),
    (0x3ff6f26008fab5a0, 0xbfd713e31351e000),
    (0x3ff6d1a61f138c7d, 0xbfd6b85b38287800),
    (0x3ff6b1490bc5b4d1, 0xbfd65d5590807800),
    (0x3ff69147332f0cba, 0xbfd602d076180000),
    (0x3ff6719f18224223, 0xbfd5a8ca86909000),
    (0x3ff6524f99a51ed9, 0xbfd54f4356035000),
    (0x3ff63356aa8f24c4, 0xbfd4f637c36b4000),
    (0x3ff614b36b9ddc14, 0xbfd49da7fda85000),
    (0x3ff5f66452c65c4c, 0xbfd445923989a800),
    (0x3ff5d867b5912c4f, 0xbfd3edf439b0b800),
    (0x3ff5babccb5b90de, 0xbfd396ce448f7000),
    (0x3ff59d61f2d91a78, 0xbfd3401e17bda000),
    (0x3ff5805612465687, 0xbfd2e9e2ef468000),
    (0x3ff56397cee76bd3, 0xbfd2941b3830e000),
    (0x3ff54725e2a77f93, 0xbfd23ec58cda8800),
    (0x3ff52aff42064583, 0xbfd1e9e129279000),
    (0x3ff50f22dbb2bddf, 0xbfd1956d2b48f800),
    (0x3ff4f38f4734ded7, 0xbfd141679ab9f800),
    (0x3ff4d843cfde2840, 0xbfd0edd094ef9800),
    (0x3ff4bd3ec078a3c8, 0xbfd09aa518db1000),
    (0x3ff4a27fc3e0258a, 0xbfd047e65263b800),
    (0x3ff4880524d48434, 0xbfcfeb224586f000),
    (0x3ff46dce1b192d0b, 0xbfcf474a7517b000),
    (0x3ff453d9d3391854, 0xbfcea4443d103000),
    (0x3ff43a2744b4845a, 0xbfce020d44e9b000),
    (0x3ff420b54115f8fb, 0xbfcd60a22977f000),
    (0x3ff40782da3ef4b1, 0xbfccc00104959000),
    (0x3ff3ee8f5d57fe8f, 0xbfcc202956891000),
    (0x3ff3d5d9a00b4ce9, 0xbfcb81178d811000),
    (0x3ff3bd60c010c12b, 0xbfcae2c9ccd3d000),
    (0x3ff3a5242b75dab8, 0xbfca45402e129000),
    (0x3ff38d22cd9fd002, 0xbfc9a877681df000),
    (0x3ff3755bc5847a1c, 0xbfc90c6d69483000),
    (0x3ff35dce49ad36e2, 0xbfc87120a645c000),
    (0x3ff34679984dd440, 0xbfc7d68fb4143000),
    (0x3ff32f5cceffcb24, 0xbfc73cb83c627000),
    (0x3ff3187775a10d49, 0xbfc6a39a9b376000),
    (0x3ff301c8373e3990, 0xbfc60b3154b7a000),
    (0x3ff2eb4ebb95f841, 0xbfc5737d76243000),
    (0x3ff2d50a0219a9d1, 0xbfc4dc7b8fc23000),
    (0x3ff2bef9a8b7fd2a, 0xbfc4462c51d20000),
    (0x3ff2a91c7a0c1bab, 0xbfc3b08abc830000),
    (0x3ff293726014b530, 0xbfc31b996b490000),
    (0x3ff27dfa5757a1f5, 0xbfc2875490a44000),
    (0x3ff268b39b1d3bbf, 0xbfc1f3b9f879a000),
    (0x3ff2539d838ff5bd, 0xbfc160c8252ca000),
    (0x3ff23eb7aac9083b, 0xbfc0ce7f57f72000),
    (0x3ff22a012ba940b6, 0xbfc03cdc49fea000),
    (0x3ff2157996cc4132, 0xbfbf57bdbc4b8000),
    (0x3ff201201dd2fc9b, 0xbfbe370896404000),
    (0x3ff1ecf4494d480b, 0xbfbd17983ef94000),
    (0x3ff1d8f5528f6569, 0xbfbbf9674ed8a000),
    (0x3ff1c52311577e7c, 0xbfbadc79202f6000),
    (0x3ff1b17c74cb26e9, 0xbfb9c0c3e7288000),
    (0x3ff19e010c2c1ab6, 0xbfb8a646b372c000),
    (0x3ff18ab07bb670bd, 0xbfb78d01b3ac0000),
    (0x3ff1778a25efbcb6, 0xbfb674f145380000),
    (0x3ff1648d354c31da, 0xbfb55e0e6d878000),
    (0x3ff151b990275fdd, 0xbfb4485cdea1e000),
    (0x3ff13f0ea432d24c, 0xbfb333d94d6aa000),
    (0x3ff12c8b7210f9da, 0xbfb22079f8c56000),
    (0x3ff11a3028ecb531, 0xbfb10e4698622000),
    (0x3ff107fbda8434af, 0xbfaffa6c6ad20000),
    (0x3ff0f5ee0f4e6bb3, 0xbfadda8d4a774000),
    (0x3ff0e4065d2a9fce, 0xbfabbcece4850000),
    (0x3ff0d244632ca521, 0xbfa9a1894012c000),
    (0x3ff0c0a77ce2981a, 0xbfa788583302c000),
    (0x3ff0af2f83c636d1, 0xbfa5715e67d68000),
    (0x3ff09ddb98a01339, 0xbfa35c8a49658000),
    (0x3ff08cabaf52e7df, 0xbfa149e364154000),
    (0x3ff07b9f2f4e28fb, 0xbf9e72c082eb8000),
    (0x3ff06ab58c358f19, 0xbf9a55f152528000),
    (0x3ff059eea5ecf92c, 0xbf963d62cf818000),
    (0x3ff04949cdd12c90, 0xbf9228fb8caa0000),
    (0x3ff038c6c6f0ada9, 0xbf8c317b20f90000),
    (0x3ff02865137932a9, 0xbf8419355daa0000),
    (0x3ff0182427ea7348, 0xbf781203c2ec0000),
    (0x3ff008040614b195, 0xbf60040979240000),
    (0x3fefe01ff726fa1a, 0x3f6feff384900000),
    (0x3fefa11cc261ea74, 0x3f87dc41353d0000),
    (0x3fef6310b081992e, 0x3f93cea3c4c28000),
    (0x3fef25f63ceeadcd, 0x3f9b9fc114890000),
    (0x3feee9c8039113e7, 0x3fa1b0d8ce110000),
    (0x3feeae8078cbb1ab, 0x3fa58a5bd001c000),
    (0x3fee741aa29d0c9b, 0x3fa95c8340d88000),
    (0x3fee3a91830a99b5, 0x3fad276aef578000),
    (0x3fee01e009609a56, 0x3fb07598e598c000),
    (0x3fedca01e577bb98, 0x3fb253f5e30d2000),
    (0x3fed92f20b7c9103, 0x3fb42edd8b380000),
    (0x3fed5cac66fb5cce, 0x3fb606598757c000),
    (0x3fed272caa5ede9d, 0x3fb7da76356a0000),
    (0x3fecf26e3e6b2ccd, 0x3fb9ab434e1c6000),
    (0x3fecbe6da2a77902, 0x3fbb78c7bb0d6000),
    (0x3fec8b266d37086d, 0x3fbd431332e72000),
    (0x3fec5894bd5d5804, 0x3fbf0a3171de6000),
    (0x3fec26b533bb9f8c, 0x3fc067152b914000),
    (0x3febf583eeece73f, 0x3fc147858292b000),
    (0x3febc4fd75db96c1, 0x3fc2266ecdca3000),
    (0x3feb951e0c864a28, 0x3fc303d7a6c55000),
    (0x3feb65e2c5ef3e2c, 0x3fc3dfc33c331000),
    (0x3feb374867c9888b, 0x3fc4ba366b7a8000),
    (0x3feb094b211d304a, 0x3fc5933928d1f000),
    (0x3feadbe885f2ef7e, 0x3fc66acd2418f000),
    (0x3feaaf1d31603da2, 0x3fc740f8ec669000),
    (0x3fea82e63fd358a7, 0x3fc815c0f51af000),
    (0x3fea5740ef09738b, 0x3fc8e92954f68000),
    (0x3fea2c2a90ab4b27, 0x3fc9bb3602f84000),
    (0x3fea01a01393f2d1, 0x3fca8bed1c2c0000),
    (0x3fe9d79f24db3c1b, 0x3fcb5b515c01d000),
    (0x3fe9ae2505c7b190, 0x3fcc2967ccbcc000),
    (0x3fe9852ef297ce2f, 0x3fccf635d5486000),
    (0x3fe95cbaeea44b75, 0x3fcdc1bd3446c000),
    (0x3fe934c69de74838, 0x3fce8c01b8cfe000),
    (0x3fe90d4f2f6752e6, 0x3fcf5509c0179000),
    (0x3fe8e6528effd79d, 0x3fd00e6c121fb800),
    (0x3fe8bfce9fcc007c, 0x3fd071b80e93d000),
    (0x3fe899c0dabec30e, 0x3fd0d46b9e867000),
    (0x3fe87427aa2317fb, 0x3fd13687334bd000),
    (0x3fe84f00acb39a08, 0x3fd1980d67234800),
    (0x3fe82a49e8653e55, 0x3fd1f8ffe0cc8000),
    (0x3fe8060195f40260, 0x3fd2595fd7636800),
    (0x3fe7e22563e0a329, 0x3fd2b9300914a800),
    (0x3fe7beb377dcb5ad, 0x3fd3187210436000),
    (0x3fe79baa679725c2, 0x3fd377266dec1800),
    (0x3fe77907f2170657, 0x3fd3d54ffbaf3000),
    (0x3fe756cadbd6130c, 0x3fd432eee32fe000),
];

/// `ln(x)`. Translation of musl `src/math/log.c` (ARM optimized-routines,
/// MIT) — the algorithm and tables glibc ≥ 2.29 ships as
/// `sysdeps/ieee754/dbl-64/e_log.c`. Worst-case error 0.52 ulp.
pub fn log(x: f64) -> f64 {
    const OFF: u64 = 0x3fe6000000000000;
    const LO: u64 = 0x3fef000000000000; /* asuint64(1.0 - 0x1p-4) */
    const HI: u64 = 0x3ff0900000000000; /* asuint64(1.0 + 0x1.09p-4) */

    let mut ix = x.to_bits();
    let top = (ix >> 48) as u32;

    if ix.wrapping_sub(LO) < HI - LO {
        /* Inputs close to 1.0 get their own polynomial. */
        if ix == 0x3ff0000000000000 {
            return 0.0;
        }
        let r = x - 1.0;
        let r2 = r * r;
        let r3 = r * r2;
        let b: [f64; 11] = {
            let mut t = [0.0f64; 11];
            let mut i = 0;
            while i < 11 {
                t[i] = f64::from_bits(LOG_POLY1[i]);
                i += 1;
            }
            t
        };
        let mut y = r3
            * (b[1]
                + r * b[2]
                + r2 * b[3]
                + r3 * (b[4] + r * b[5] + r2 * b[6] + r3 * (b[7] + r * b[8] + r2 * b[9] + r3 * b[10])));
        let w = r * f64::from_bits(0x41a0000000000000); /* 0x1p27 */
        let rhi = r + w - w;
        let rlo = r - rhi;
        let w = rhi * rhi * b[0]; /* b[0] == -0.5 */
        let hi = r + w;
        let lo = r - hi + w + b[0] * rlo * (rhi + r);
        y += lo;
        y += hi;
        return y;
    }
    if top.wrapping_sub(0x0010) >= 0x7ff0 - 0x0010 {
        /* x < 0x1p-1022, or inf, or nan. */
        if ix.wrapping_mul(2) == 0 {
            return f64::NEG_INFINITY; /* __math_divzero(1) */
        }
        if ix == f64::INFINITY.to_bits() {
            return x;
        }
        if (top & 0x8000) != 0 || (top & 0x7ff0) == 0x7ff0 {
            return f64::NAN; /* __math_invalid(x) */
        }
        /* x is subnormal: normalize it. */
        ix = (x * f64::from_bits(0x4330000000000000)).to_bits(); /* 0x1p52 */
        ix = ix.wrapping_sub(52u64 << 52);
    }

    /* x = 2^k z; z in [OFF, 2*OFF), exact. */
    let tmp = ix.wrapping_sub(OFF);
    let i = ((tmp >> (52 - 7)) % 128) as usize; /* LOG_TABLE_BITS = 7 */
    let k = (tmp as i64) >> 52; /* arithmetic shift */
    let iz = ix.wrapping_sub(tmp & (0xfffu64 << 52));
    let invc = f64::from_bits(LOG_TAB[i].0);
    let logc = f64::from_bits(LOG_TAB[i].1);
    let z = f64::from_bits(iz);

    /* r ~= z/c - 1, |r| < 1/(2*N); the FMA path, as on x86-64. */
    let r = z.mul_add(invc, -1.0);
    let kd = k as f64;

    let w = kd * f64::from_bits(LOG_LN2HI) + logc;
    let hi = w + r;
    let lo = w - hi + r + kd * f64::from_bits(LOG_LN2LO);

    let r2 = r * r;
    let a0 = f64::from_bits(LOG_POLY[0]);
    let a1 = f64::from_bits(LOG_POLY[1]);
    let a2 = f64::from_bits(LOG_POLY[2]);
    let a3 = f64::from_bits(LOG_POLY[3]);
    let a4 = f64::from_bits(LOG_POLY[4]);
    lo + r2 * a0 + r * r2 * (a1 + r * a2 + r2 * (a3 + r * a4)) + hi
}

/* =====================================================================
 * exp and log in double-double
 * =====================================================================
 * These two kernels carry ~106 significant bits, which is what lets
 * expm1, log1p, sinh, cosh and acosh below be *correctly rounded* rather
 * than merely faithful. glibc's own versions of those five are the
 * SunPro fdlibm kernels and measure 0.79 to 1.75 ulp on this host
 * (`tools/libm_differential.sh`), so the pure-Rust routines are strictly
 * more accurate; they are not, and cannot be, bit-identical to them.
 */

/// `e^x = m * 2^k` with `m` in `[1/sqrt(2), sqrt(2)]`, to ~2^-100
/// relative. Keeping the power of two separate is what lets `sinh` and
/// `cosh` stay correctly rounded right up to the overflow threshold,
/// where `e^x` itself is no longer representable.
fn exp_dd_scaled(x: f64) -> (Dd, i32) {
    /* x = k*ln2 + r, |r| <= ln2/2 */
    let k = (x * core::f64::consts::LOG2_E).round();
    let r = dd_sub(dd(x), dd_mul_d(Dd(LN2_DD.0, LN2_DD.1), k));
    /* exp(r) = sum r^n / n!, 25 terms cover |r| <= ln2/2 to 2^-107 */
    let mut p = Dd(INV_FACT[24].0, INV_FACT[24].1);
    for c in INV_FACT[..24].iter().rev() {
        p = dd_add(dd_mul(p, r), Dd(c.0, c.1));
    }
    (p, k as i32)
}

/// Multiply a double-double by `2^k` exactly, splitting the scaling so no
/// intermediate overflows for any `k` a finite result can need.
fn dd_ldexp(a: Dd, k: i32) -> Dd {
    let k1 = k / 2;
    dd_scale2(dd_scale2(a, exp2i(k1)), exp2i(k - k1))
}

/// `e^x` to ~2^-100 relative, as a double-double.
fn exp_dd(x: f64) -> Dd {
    let (m, k) = exp_dd_scaled(x);
    dd_ldexp(m, k)
}

/// `ln(w)` to ~2^-100 relative, as a double-double, for `w > 0`.
/// Accurate for `w` arbitrarily close to 1 because the reduction keeps
/// `w - 1` in double-double form.
fn log_dd(w: Dd) -> Dd {
    /* w = 2^k * m with m in [1, 2) */
    let k = ((w.0.to_bits() >> 52) & 0x7ff) as i32 - 1023;
    let m = dd_scale2(w, exp2i(-k));
    /* m / (1 + j/64) lands within 1/128 of 1 */
    let j = ((m.0 - 1.0) * 64.0).round();
    let c = 1.0 + j / 64.0; /* exact */
    let u = dd_div(m, dd(c));
    /* z = (u-1)/(u+1), |z| <= 1/256; log(u) = 2*atanh(z) */
    let num = dd_add_d(u, -1.0);
    let den = dd_add_d(u, 1.0);
    let z = dd_div(num, den);
    let z2 = dd_mul(z, z);
    let mut p = Dd(ATANH_COEF[9].0, ATANH_COEF[9].1);
    for a in ATANH_COEF[..9].iter().rev() {
        p = dd_add(dd_mul(p, z2), Dd(a.0, a.1));
    }
    let log_u = dd_scale2(dd_mul(z, p), 2.0);
    let e = &LOG_TAB_DD[j as usize];
    let mut r = dd_add(Dd(e.0, e.1), log_u);
    if k != 0 {
        r = dd_add(r, dd_mul_d(Dd(LN2_DD.0, LN2_DD.1), k as f64));
    }
    r
}

/* =====================================================================
 * expm1 / log1p / sinh / cosh / acosh — correctly rounded
 * ===================================================================== */

/// `e^x - 1`, correctly rounded. The subtraction that cancels in
/// `exp(x) - 1` is avoided by summing the Taylor series without its
/// leading 1 whenever `|x|` is small.
pub fn expm1(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }
    if x == f64::NEG_INFINITY {
        return -1.0;
    }
    if x == f64::INFINITY {
        return x;
    }
    if x == 0.0 {
        return x; /* preserve -0.0 */
    }
    if x.abs() < exp2i(-54) {
        /* expm1(x) == x to within half an ulp, and this avoids
        underflow bookkeeping in the series */
        return x;
    }
    if x > 709.782712893384 {
        return f64::INFINITY;
    }
    if x < -40.0 {
        /* exp(x) is below 2^-58, so expm1(x) rounds to exp(x) - 1 */
        return exp_dd(x).value() - 1.0;
    }
    if x.abs() <= 0.5 {
        /* sum_{n>=1} x^n / n!, i.e. x * sum_{n>=0} x^n/(n+1)! */
        let xd = dd(x);
        let mut p = Dd(INV_FACT[24].0, INV_FACT[24].1);
        for c in INV_FACT[1..24].iter().rev() {
            p = dd_add(dd_mul(p, xd), Dd(c.0, c.1));
        }
        return dd_mul(xd, p).value();
    }
    dd_add_d(exp_dd(x), -1.0).value()
}

/// `ln(1 + x)`, correctly rounded. `1 + x` is formed exactly as a
/// double-double, so no information is lost for tiny `x`.
pub fn log1p(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }
    if x < -1.0 {
        return f64::NAN;
    }
    if x == -1.0 {
        return f64::NEG_INFINITY;
    }
    if x == f64::INFINITY {
        return x;
    }
    if x == 0.0 {
        return x; /* preserve -0.0 */
    }
    if x.abs() < exp2i(-54) {
        return x;
    }
    let (h, l) = two_sum(1.0, x);
    log_dd(Dd(h, l)).value()
}

/// `sinh(x)`, correctly rounded.
pub fn sinh(x: f64) -> f64 {
    if !x.is_finite() || x == 0.0 {
        return x;
    }
    let a = x.abs();
    if a < exp2i(-27) {
        return x;
    }
    let r = if a <= 0.5 {
        /* sum over odd n of x^n/n! -- no cancellation */
        let xd = dd(a);
        let x2 = dd_mul(xd, xd);
        let mut p = Dd(INV_FACT[23].0, INV_FACT[23].1);
        let mut n: i32 = 21;
        while n >= 1 {
            let c = &INV_FACT[n as usize];
            p = dd_add(dd_mul(p, x2), Dd(c.0, c.1));
            n -= 2;
        }
        dd_mul(xd, p).value()
    } else {
        /* e^a = m*2^k, so sinh(a) = 2^(k-1) * (m - 2^(-2k)/m) */
        let (m, k) = exp_dd_scaled(a);
        let t = if k > 80 {
            Dd(0.0, 0.0)
        } else {
            dd_ldexp(dd_div(dd(1.0), m), -2 * k)
        };
        dd_ldexp(dd_sub(m, t), k - 1).value()
    };
    if x < 0.0 {
        -r
    } else {
        r
    }
}

/// `cosh(x)`, correctly rounded.
pub fn cosh(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }
    let a = x.abs();
    if a.is_infinite() {
        return f64::INFINITY;
    }
    if a < exp2i(-27) {
        return 1.0;
    }
    /* e^a = m*2^k, so cosh(a) = 2^(k-1) * (m + 2^(-2k)/m) */
    let (m, k) = exp_dd_scaled(a);
    let t = if k > 80 {
        Dd(0.0, 0.0)
    } else {
        dd_ldexp(dd_div(dd(1.0), m), -2 * k)
    };
    dd_ldexp(dd_add(m, t), k - 1).value()
}

/// `acosh(x) = ln(x + sqrt(x*x - 1))`, correctly rounded.
pub fn acosh(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }
    if x < 1.0 {
        return f64::NAN;
    }
    if x == 1.0 {
        return 0.0;
    }
    if x == f64::INFINITY {
        return x;
    }
    if x < 1.5 {
        /* w = 1 + t + sqrt(t*(t+2)) with t = x-1, kept in double-double so
        that the small-t cancellation of x*x - 1 never happens */
        let t = dd_add_d(dd(x), -1.0);
        let s = dd_sqrt(dd_mul(t, dd_add_d(t, 2.0)));
        return log_dd(dd_add_d(dd_add(t, s), 1.0)).value();
    }
    if x < exp2i(500) {
        let x2 = dd_mul(dd(x), dd(x));
        let s = dd_sqrt(dd_add_d(x2, -1.0));
        return log_dd(dd_add(dd(x), s)).value();
    }
    /* x*x would overflow: acosh(x) = log(x) + ln2 to full precision */
    dd_add(log_dd(dd(x)), Dd(LN2_DD.0, LN2_DD.1)).value()
}

/* =====================================================================
 * pow — the deterministic routine already proven in sundials_math.rs
 * ===================================================================== */

/// `x^y`. Forwards to the ARM optimized-routines `pow` translated in
/// [`crate::sundials_math`], which `tools/pow_differential.sh` measures
/// bit-exact against the native glibc `pow`.
#[inline]
pub fn pow(x: f64, y: f64) -> f64 {
    pow_glibc(x, y)
}

/* =====================================================================
 * Payne-Hanek argument reduction for sin / cos
 * =====================================================================
 * Computes `n = round(x / (pi/2))` and `r = x - n*(pi/2)` with `r`
 * carried as a double-double whose *relative* accuracy is ~2^-128, so
 * no cancellation is lost even when `x` lands very close to a multiple
 * of pi/2. The reduction is exact integer arithmetic on the bits of
 * 2/pi, so its cost and its accuracy are both independent of |x|.
 */

/// 384-bit little-endian magnitude: `p[0]` is least significant.
type Big = [u64; 6];

/// 64 bits of `p` starting at bit index `from` (0 = least significant).
fn big_bits_at(p: &Big, from: usize) -> u64 {
    let w = from / 64;
    let o = from % 64;
    let lo = if w < 6 { p[w] } else { 0 };
    if o == 0 {
        return lo;
    }
    let hi = if w + 1 < 6 { p[w + 1] } else { 0 };
    (lo >> o) | (hi << (64 - o))
}

/// Index of the highest set bit of `p`, or `None` when `p` is zero.
fn big_bit_len(p: &Big) -> Option<usize> {
    for w in (0..6).rev() {
        if p[w] != 0 {
            return Some(w * 64 + (64 - p[w].leading_zeros() as usize));
        }
    }
    None
}

/// `p <- 2^bits - p`, for `p < 2^bits` and `bits <= 384`.
fn big_complement(p: &mut Big, bits: usize) {
    /* mask p to `bits`, then two's-complement it within that width */
    let full = bits / 64;
    let rem = bits % 64;
    for (w, slot) in p.iter_mut().enumerate() {
        if w < full {
            continue;
        } else if w == full && rem != 0 {
            *slot &= (1u64 << rem) - 1;
        } else {
            *slot = 0;
        }
    }
    let mut borrow = 1u64;
    for (w, slot) in p.iter_mut().enumerate() {
        let (v, b1) = (!*slot).overflowing_add(borrow);
        *slot = v;
        borrow = u64::from(b1);
        let _ = w;
    }
    /* re-mask: the complement is only meaningful within `bits` */
    for (w, slot) in p.iter_mut().enumerate() {
        if w < full {
            continue;
        } else if w == full && rem != 0 {
            *slot &= (1u64 << rem) - 1;
        } else if w >= full {
            *slot = 0;
        }
    }
}

/// Convert the top 128 significant bits of a magnitude to a double-double.
/// `m128` must have its bit 127 set; the returned pair equals
/// `m128 * 2^scale_exp` exactly to within 2^-128 relative.
fn u128_to_dd(m128: u128, scale_exp: i32) -> Dd {
    /* three chunks small enough to convert to f64 without rounding */
    let c0 = (m128 >> 86) as u64; /* 42 bits */
    let c1 = ((m128 >> 43) & ((1u64 << 43) as u128 - 1)) as u64; /* 43 bits */
    let c2 = (m128 & ((1u64 << 43) as u128 - 1)) as u64; /* 43 bits */
    let mut v = dd(c0 as f64 * exp2i(86 + scale_exp));
    v = dd_add_d(v, c1 as f64 * exp2i(43 + scale_exp));
    v = dd_add_d(v, c2 as f64 * exp2i(scale_exp));
    v
}

/// `2^n` for `n` in the normal range, built directly from the exponent field.
#[inline]
fn exp2i(n: i32) -> f64 {
    if n >= -1022 && n <= 1023 {
        f64::from_bits(((n + 1023) as u64) << 52)
    } else if n > 1023 {
        f64::INFINITY
    } else {
        /* split the scaling so the intermediate stays normal */
        let a = f64::from_bits(((-1022 + 1023) as u64) << 52);
        let mut r = a;
        let mut k = n + 1022;
        while k < -1022 {
            r *= a;
            k += 1022;
        }
        r * f64::from_bits(((k + 1023) as u64) << 52)
    }
}

/// Returns `(n mod 4, r)` with `x = n*(pi/2) + r` and `|r| <= pi/4`.
fn rem_pio2(x: f64) -> (u32, Dd) {
    let ix = x.to_bits();
    let sign = (ix >> 63) != 0;
    let ax = f64::from_bits(ix & (u64::MAX / 2));

    /* |x| <= pi/4: nothing to do. */
    if ax <= PI_OVER_4_DD.0 {
        return (0, dd(x));
    }

    /* Decompose |x| = m * 2^e with m a 53-bit integer. */
    let biased = ((ix >> 52) & 0x7ff) as i32;
    let (m, e) = if biased == 0 {
        /* subnormal: unreachable here because |x| > pi/4, but kept total */
        ((ix & 0x000f_ffff_ffff_ffff), -1074i32)
    } else {
        ((ix & 0x000f_ffff_ffff_ffff) | (1u64 << 52), biased - 1075)
    };

    /* Bits of 2/pi are indexed from 1 (the first fractional bit). Every
    term of m*2^e*(2/pi) whose weight is >= 4 is a multiple of 4 and so
    cannot affect the quadrant, which is why the window can start at
    bit e-1. */
    let b0: i32 = if e - 1 >= 1 { e - 1 } else { 1 };
    let start = (b0 - 1) as usize; /* 0-indexed into the bit stream */
    let wi = start / 64;
    let off = start % 64;

    /* 320-bit window of 2/pi, most significant word first */
    let mut u = [0u64; 5];
    for (i, slot) in u.iter_mut().enumerate() {
        let a = *TWO_OVER_PI.get(wi + i).unwrap_or(&0);
        let b = *TWO_OVER_PI.get(wi + i + 1).unwrap_or(&0);
        *slot = if off == 0 { a } else { (a << off) | (b >> (64 - off)) };
    }

    /* p = m * u, a 384-bit product (little-endian words) */
    let mut p: Big = [0; 6];
    let mut carry: u128 = 0;
    for i in 0..5 {
        let t = (m as u128) * (u[4 - i] as u128) + carry;
        p[i] = t as u64;
        carry = t >> 64;
    }
    p[5] = carry as u64;

    /* The binary point of p sits at bit `pt`: the window value is
    u * 2^-320, so p = m*u and x*2/pi == p * 2^(e - b0 + 1 - 320). */
    let pt = (320 - (e - b0 + 1)) as usize;

    /* integer part (mod 4) and the fractional bits */
    let int2 = (big_bits_at(&p, pt) & 3) as u32;
    let half_set = pt > 0 && (big_bits_at(&p, pt - 1) & 1) == 1;

    let mut frac = p;
    /* clear everything at or above the binary point */
    {
        let full = pt / 64;
        let rem = pt % 64;
        for (w, slot) in frac.iter_mut().enumerate() {
            if w < full {
                continue;
            } else if w == full && rem != 0 {
                *slot &= (1u64 << rem) - 1;
            } else {
                *slot = 0;
            }
        }
    }

    let (mut n, negative) = if half_set {
        /* round up: r becomes negative, magnitude 1 - frac */
        big_complement(&mut frac, pt);
        (int2.wrapping_add(1) & 3, true)
    } else {
        (int2, false)
    };

    /* frac * 2^-pt in [0, 1/2] -> double-double, keeping 128 significant
    bits *counted from the leading one*, so tiny remainders keep their
    full relative accuracy. */
    let f = match big_bit_len(&frac) {
        None => Dd(0.0, 0.0),
        Some(len) => {
            let m128: u128 = if len >= 128 {
                ((big_bits_at(&frac, len - 64) as u128) << 64)
                    | (big_bits_at(&frac, len - 128) as u128)
            } else {
                let lo = ((big_bits_at(&frac, 0) as u128)
                    | ((big_bits_at(&frac, 64) as u128) << 64))
                    << (128 - len);
                lo
            };
            u128_to_dd(m128, len as i32 - 128 - pt as i32)
        }
    };

    /* r = +- f * (pi/2), evaluated with pi/2 as a triple-double */
    let mut r = dd_mul(f, Dd(PI_OVER_2.0, PI_OVER_2.1));
    r = dd_add_d(r, f.0 * PI_OVER_2.2);
    if negative {
        r = dd_neg(r);
    }
    if sign {
        r = dd_neg(r);
        n = 4 - n;
        if n == 4 {
            n = 0;
        }
    }
    (n & 3, r)
}

/// `sin(r)` for `|r| <= pi/4`, carried in double-double.
fn sin_kernel(r: Dd) -> Dd {
    let z = dd_mul(r, r);
    let mut p = Dd(SIN_COEF[14].0, SIN_COEF[14].1);
    for c in SIN_COEF[..14].iter().rev() {
        p = dd_add(dd_mul(p, z), Dd(c.0, c.1));
    }
    dd_mul(r, p)
}

/// `cos(r)` for `|r| <= pi/4`, carried in double-double.
fn cos_kernel(r: Dd) -> Dd {
    let z = dd_mul(r, r);
    let mut p = Dd(COS_COEF[14].0, COS_COEF[14].1);
    for c in COS_COEF[..14].iter().rev() {
        p = dd_add(dd_mul(p, z), Dd(c.0, c.1));
    }
    p
}

/// `sin(x)`, correctly rounded except with probability ~2^-45 per call
/// (the internal accuracy is ~2^-100 before the single final rounding).
pub fn sin(x: f64) -> f64 {
    if !x.is_finite() {
        return x - x; /* NaN, and NaN for +-inf */
    }
    if x == 0.0 {
        return x; /* preserve -0.0 */
    }
    let (n, r) = rem_pio2(x);
    match n {
        0 => sin_kernel(r).value(),
        1 => cos_kernel(r).value(),
        2 => -sin_kernel(r).value(),
        _ => -cos_kernel(r).value(),
    }
}

/// `cos(x)`, correctly rounded except with probability ~2^-45 per call.
pub fn cos(x: f64) -> f64 {
    if !x.is_finite() {
        return x - x;
    }
    let (n, r) = rem_pio2(x);
    match n {
        0 => cos_kernel(r).value(),
        1 => -sin_kernel(r).value(),
        2 => -cos_kernel(r).value(),
        _ => sin_kernel(r).value(),
    }
}

/* =====================================================================
 * atan / asin / acos — double-double
 * ===================================================================== */

/// `atan(t)` for `|t| <= 1/32`, carried in double-double.
fn atan_series(t: Dd) -> Dd {
    let z = dd_mul(t, t);
    let mut p = Dd(ATAN_COEF[11].0, ATAN_COEF[11].1);
    for c in ATAN_COEF[..11].iter().rev() {
        p = dd_add(dd_mul(p, z), Dd(c.0, c.1));
    }
    dd_mul(t, p)
}

/// `atan(u)` for `0 <= u <= 1`, carried in double-double.
fn atan_unit(u: f64) -> Dd {
    let k = (u * 16.0).round();
    let c = k / 16.0; /* exact: k is an integer <= 16 */
    /* t = (u - c) / (1 + u*c), |t| <= 1/32 */
    let (nh, nl) = two_sum(u, -c);
    let num = Dd(nh, nl);
    let (dh, dl) = two_prod(u, c);
    let den = dd_add_d(Dd(dh, dl), 1.0);
    let t = dd_div(num, den);
    let e = &ATAN_TAB[k as usize];
    dd_add(Dd(e.0, e.1), atan_series(t))
}

/// `atan(x)`, correctly rounded except with probability ~2^-45 per call.
pub fn atan(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }
    let neg = x.is_sign_negative();
    let a = x.abs();
    let r = if a.is_infinite() {
        Dd(PI_OVER_2.0, PI_OVER_2.1)
    } else if a <= 1.0 {
        atan_unit(a)
    } else {
        /* atan(a) = pi/2 - atan(1/a) */
        let inv = dd_div(dd(1.0), dd(a));
        let small = atan_unit_dd(inv);
        dd_sub(Dd(PI_OVER_2.0, PI_OVER_2.1), small)
    };
    let v = r.value();
    if neg {
        -v
    } else {
        v
    }
}

/// `atan(u)` for a double-double `0 <= u <= 1`.
fn atan_unit_dd(u: Dd) -> Dd {
    let k = (u.0 * 16.0).round();
    let c = k / 16.0;
    let num = dd_add_d(u, -c);
    let den = dd_add_d(dd_mul_d(u, c), 1.0);
    let t = dd_div(num, den);
    let e = &ATAN_TAB[k as usize];
    dd_add(Dd(e.0, e.1), atan_series(t))
}

/// `asin(u)` for `0 <= u <= 1`, carried in double-double.
fn asin_pos(u: f64) -> Dd {
    if u <= 0.7 {
        /* asin(u) = atan(u / sqrt(1 - u^2)) */
        let u2 = dd_mul(dd(u), dd(u));
        let s = dd_sqrt(dd_sub(dd(1.0), u2));
        let q = dd_div(dd(u), s);
        atan_unit_dd(q)
    } else {
        /* asin(u) = pi/2 - 2*asin(sqrt((1-u)/2)) */
        let w = dd_scale2(dd_add_d(dd(-u), 1.0), 0.5);
        let s = dd_sqrt(w);
        /* s <= sqrt(0.15) < 0.39, so the atan branch above is in range */
        let s2 = dd_mul(s, s);
        let d = dd_sqrt(dd_sub(dd(1.0), s2));
        let inner = atan_unit_dd(dd_div(s, d));
        dd_sub(Dd(PI_OVER_2.0, PI_OVER_2.1), dd_scale2(inner, 2.0))
    }
}

/// `asin(x)`, correctly rounded except with probability ~2^-45 per call.
pub fn asin(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }
    let a = x.abs();
    if a > 1.0 {
        return f64::NAN;
    }
    if a == 1.0 {
        return (PI_OVER_2.0 + PI_OVER_2.1).copysign(x);
    }
    let v = asin_pos(a).value();
    if x.is_sign_negative() {
        -v
    } else {
        v
    }
}

/// `acos(x)`, correctly rounded except with probability ~2^-45 per call.
pub fn acos(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }
    let a = x.abs();
    if a > 1.0 {
        return f64::NAN;
    }
    if x == 1.0 {
        return 0.0;
    }
    if x == -1.0 {
        return PI_DD.0 + PI_DD.1;
    }
    if x >= 0.0 {
        /* acos(x) = 2*asin(sqrt((1-x)/2)) — no cancellation near x = 1 */
        let w = dd_scale2(dd_add_d(dd(-x), 1.0), 0.5);
        let s = dd_sqrt(w);
        let s2 = dd_mul(s, s);
        let d = dd_sqrt(dd_sub(dd(1.0), s2));
        dd_scale2(atan_unit_dd(dd_div(s, d)), 2.0).value()
    } else {
        /* acos(x) = pi - 2*asin(sqrt((1+x)/2)) */
        let w = dd_scale2(dd_add_d(dd(x), 1.0), 0.5);
        let s = dd_sqrt(w);
        let s2 = dd_mul(s, s);
        let d = dd_sqrt(dd_sub(dd(1.0), s2));
        let inner = dd_scale2(atan_unit_dd(dd_div(s, d)), 2.0);
        dd_sub(Dd(PI_DD.0, PI_DD.1), inner).value()
    }
}

/* =====================================================================
 * Method-call surface
 * =====================================================================
 * Rust resolves inherent methods before trait methods, so `x.sin()` can
 * never be redirected to this module by a trait. The port therefore
 * spells the calls `x.sun_sin()`: a one-token rename that keeps the
 * translated examples reading like their C parents while making the
 * host libm unreachable. `sqrt`, `mul_add`, `abs`, `ceil`, `round` and
 * `copysign` keep their inherent spellings — IEEE-754 specifies them
 * exactly, so they are identical on every target.
 */

/// The pure-Rust elementary functions in method position.
pub trait SunMath {
    /// `e^x` — see [`exp`].
    fn sun_exp(self) -> f64;
    /// `ln(x)` — see [`log`].
    fn sun_ln(self) -> f64;
    /// `e^x - 1` — see [`expm1`].
    fn sun_exp_m1(self) -> f64;
    /// `ln(1 + x)` — see [`log1p`].
    fn sun_ln_1p(self) -> f64;
    /// `sin(x)` — see [`sin`].
    fn sun_sin(self) -> f64;
    /// `cos(x)` — see [`cos`].
    fn sun_cos(self) -> f64;
    /// `atan(x)` — see [`atan`].
    fn sun_atan(self) -> f64;
    /// `asin(x)` — see [`asin`].
    fn sun_asin(self) -> f64;
    /// `acos(x)` — see [`acos`].
    fn sun_acos(self) -> f64;
    /// `sinh(x)` — see [`sinh`].
    fn sun_sinh(self) -> f64;
    /// `cosh(x)` — see [`cosh`].
    fn sun_cosh(self) -> f64;
    /// `acosh(x)` — see [`acosh`].
    fn sun_acosh(self) -> f64;
    /// `x^y` — see [`pow`].
    fn sun_powf(self, y: f64) -> f64;
}

/// The default: every function comes from this module.
#[cfg(not(feature = "host-libm"))]
impl SunMath for f64 {
    #[inline]
    fn sun_exp(self) -> f64 {
        exp(self)
    }
    #[inline]
    fn sun_ln(self) -> f64 {
        log(self)
    }
    #[inline]
    fn sun_exp_m1(self) -> f64 {
        expm1(self)
    }
    #[inline]
    fn sun_ln_1p(self) -> f64 {
        log1p(self)
    }
    #[inline]
    fn sun_sin(self) -> f64 {
        sin(self)
    }
    #[inline]
    fn sun_cos(self) -> f64 {
        cos(self)
    }
    #[inline]
    fn sun_atan(self) -> f64 {
        atan(self)
    }
    #[inline]
    fn sun_asin(self) -> f64 {
        asin(self)
    }
    #[inline]
    fn sun_acos(self) -> f64 {
        acos(self)
    }
    #[inline]
    fn sun_sinh(self) -> f64 {
        sinh(self)
    }
    #[inline]
    fn sun_cosh(self) -> f64 {
        cosh(self)
    }
    #[inline]
    fn sun_acosh(self) -> f64 {
        acosh(self)
    }
    #[inline]
    fn sun_powf(self, y: f64) -> f64 {
        pow(self, y)
    }
}

/// Diagnostic build (`--features host-libm`): every function comes from
/// the host C library instead, so a divergence can be attributed.
/// See `tools/ab_host_libm.sh`.
#[cfg(feature = "host-libm")]
impl SunMath for f64 {
    #[inline]
    fn sun_exp(self) -> f64 {
        self.exp()
    }
    #[inline]
    fn sun_ln(self) -> f64 {
        self.ln()
    }
    #[inline]
    fn sun_exp_m1(self) -> f64 {
        self.exp_m1()
    }
    #[inline]
    fn sun_ln_1p(self) -> f64 {
        self.ln_1p()
    }
    #[inline]
    fn sun_sin(self) -> f64 {
        self.sin()
    }
    #[inline]
    fn sun_cos(self) -> f64 {
        self.cos()
    }
    #[inline]
    fn sun_atan(self) -> f64 {
        self.atan()
    }
    #[inline]
    fn sun_asin(self) -> f64 {
        self.asin()
    }
    #[inline]
    fn sun_acos(self) -> f64 {
        self.acos()
    }
    #[inline]
    fn sun_sinh(self) -> f64 {
        self.sinh()
    }
    #[inline]
    fn sun_cosh(self) -> f64 {
        self.cosh()
    }
    #[inline]
    fn sun_acosh(self) -> f64 {
        self.acosh()
    }
    #[inline]
    fn sun_powf(self, y: f64) -> f64 {
        self.powf(y)
    }
}

/* =====================================================================
 * Tests
 * ===================================================================== */

#[cfg(test)]
mod tests {
    use super::*;

    /* ---------------- exact / special values ---------------- */

    #[test]
    fn libm_special_values() {
        assert_eq!(exp(0.0), 1.0);
        assert_eq!(exp(f64::NEG_INFINITY), 0.0);
        assert_eq!(exp(f64::INFINITY), f64::INFINITY);
        assert!(exp(f64::NAN).is_nan());
        assert_eq!(exp(1000.0), f64::INFINITY);
        assert_eq!(exp(-1000.0), 0.0);

        assert_eq!(log(1.0), 0.0);
        assert_eq!(log(0.0), f64::NEG_INFINITY);
        assert_eq!(log(f64::INFINITY), f64::INFINITY);
        assert!(log(-1.0).is_nan());

        assert_eq!(expm1(0.0), 0.0);
        assert_eq!(expm1(f64::NEG_INFINITY), -1.0);
        assert_eq!(log1p(0.0), 0.0);
        assert_eq!(log1p(-1.0), f64::NEG_INFINITY);
        assert!(log1p(-2.0).is_nan());

        assert_eq!(sin(0.0), 0.0);
        assert!(sin(0.0).is_sign_positive());
        assert!(sin(-0.0).is_sign_negative());
        assert_eq!(cos(0.0), 1.0);
        assert!(sin(f64::INFINITY).is_nan());
        assert!(cos(f64::NAN).is_nan());

        assert_eq!(atan(0.0), 0.0);
        assert_eq!(atan(f64::INFINITY), PI_OVER_2.0 + PI_OVER_2.1);
        assert_eq!(atan(f64::NEG_INFINITY), -(PI_OVER_2.0 + PI_OVER_2.1));
        assert_eq!(asin(0.0), 0.0);
        assert_eq!(acos(1.0), 0.0);
        assert_eq!(acos(-1.0), PI_DD.0 + PI_DD.1);
        assert!(asin(1.5).is_nan());
        assert!(acos(-1.5).is_nan());

        assert_eq!(sinh(0.0), 0.0);
        assert_eq!(cosh(0.0), 1.0);
        assert_eq!(acosh(1.0), 0.0);
        assert_eq!(cosh(f64::INFINITY), f64::INFINITY);
        assert_eq!(sinh(f64::NEG_INFINITY), f64::NEG_INFINITY);

        assert_eq!(pow(2.0, 10.0), 1024.0);
    }

    /* ---------------- identities that must hold to <= 2 ulp ------------- */

    fn close(a: f64, b: f64, ulps: f64) -> bool {
        if a == b {
            return true;
        }
        let u = (b.abs().max(f64::MIN_POSITIVE)) * f64::EPSILON;
        (a - b).abs() <= ulps * u
    }

    #[test]
    fn libm_identities() {
        let mut x = -3.0f64;
        while x < 3.0 {
            assert!(close(sin(x) * sin(x) + cos(x) * cos(x), 1.0, 4.0), "pythag at {x}");
            /* 1 + expm1(x) re-introduces the cancellation expm1 exists to
            avoid, so the tolerance has to absorb it. */
            assert!(
                close(exp(x), 1.0 + expm1(x), 4.0 + 4.0 / exp(x).max(f64::MIN_POSITIVE)),
                "expm1 at {x}"
            );
            if x.abs() < 1.5 {
                /* atan(tan(x)) == x for |x| < pi/2 */
                assert!(close(atan(sin(x) / cos(x)), x, 8.0), "atan(tan) at {x}");
            }
            if x > -0.9 {
                assert!(close(log1p(x), log(1.0 + x), 8.0), "log1p at {x}");
            }
            /* cosh^2 - sinh^2 cancels catastrophically: the two terms are
            each ~cosh(x)^2, so the tolerance has to grow with them. */
            let amp = cosh(x) * cosh(x);
            assert!(
                close(cosh(x) * cosh(x) - sinh(x) * sinh(x), 1.0, 8.0 * amp),
                "hyperbolic at {x}"
            );
            assert!(close(acosh(cosh(x)), x.abs(), 1e8), "acosh(cosh) at {x}");
            x += 0.0625;
        }
        let mut u = -1.0f64;
        while u <= 1.0 {
            assert!((sin(asin(u)) - u).abs() <= 8.0 * f64::EPSILON, "asin at {u}");
            /* cos(acos(u)) near u = 0 is a difference of quantities near
            pi/2, so only an absolute bound is meaningful there. */
            assert!((cos(acos(u)) - u).abs() <= 8.0 * f64::EPSILON, "acos at {u}");
            assert!(close(asin(u) + acos(u), PI_OVER_2.0, 4.0), "asin+acos at {u}");
            u += 1.0 / 64.0;
        }
        /* exact-ish anchors */
        assert!(close(sin(PI_DD.0 / 6.0), 0.5, 4.0));
        assert!(close(cos(PI_DD.0 / 3.0), 0.5, 4.0));
        assert!(close(atan(1.0), PI_OVER_4_DD.0, 1.0));
        assert!(close(log(exp(1.0)), 1.0, 2.0));
    }

    /// Huge arguments: the Payne-Hanek reduction must stay accurate where a
    /// Cody-Waite reduction would collapse.
    #[test]
    fn libm_huge_argument_reduction() {
        /* sin/cos of large powers of two must stay bounded and satisfy the
        Pythagorean identity, which they cannot if the reduction is lossy. */
        for k in 0..1000 {
            let x = (1.0f64 + (k as f64) / 512.0) * exp2i(k % 900);
            let s = sin(x);
            let c = cos(x);
            assert!(s.abs() <= 1.0 && c.abs() <= 1.0, "range at 2^{k}");
            assert!(close(s * s + c * c, 1.0, 8.0), "pythag at x = {x:e}");
        }
        /* x = 2^1023 is far beyond any Cody-Waite window */
        let x = exp2i(1023);
        assert!(close(sin(x) * sin(x) + cos(x) * cos(x), 1.0, 8.0));
    }

    /* ---------------- differential against the host libm ---------------- */

    struct Rec {
        x: f64,
        host: f64,
        cr: f64,
        resid: f64,
    }

    fn load(func: &str, corpus: &str) -> Option<Vec<Rec>> {
        let dir = std::env::var("SUNDIALS_LIBM_ORACLE_DIR").ok()?;
        let path = std::path::Path::new(&dir).join(format!("{func}_{corpus}.bin"));
        let blob = std::fs::read(&path).ok()?;
        let mut v = Vec::with_capacity(blob.len() / 32);
        for c in blob.chunks_exact(32) {
            let g = |i: usize| {
                let mut w = [0u8; 8];
                w.copy_from_slice(&c[i * 8..i * 8 + 8]);
                f64::from_bits(u64::from_le_bytes(w))
            };
            v.push(Rec { x: g(0), host: g(1), cr: g(2), resid: g(3) });
        }
        Some(v)
    }

    /// Error of `got` relative to the 113-bit value, in ulp of the
    /// correctly rounded result. `resid` carries the sub-ulp remainder the
    /// oracle measured, so this is a real number, not an integer count.
    fn ulp_error(got: f64, r: &Rec) -> Option<f64> {
        if !got.is_finite() || !r.cr.is_finite() {
            return None;
        }
        let u = {
            let n = f64::from_bits(r.cr.abs().to_bits() + 1);
            n - r.cr.abs()
        };
        if u == 0.0 || !u.is_finite() {
            return None;
        }
        Some((got - r.cr) / u - r.resid)
    }

    struct Report {
        n: usize,
        agree: usize,
        rust_max: f64,
        host_max: f64,
        first_x: f64,
    }

    fn measure(func: &str, corpus: &str, f: fn(f64) -> f64) -> Option<Report> {
        let recs = load(func, corpus)?;
        let mut rep = Report { n: 0, agree: 0, rust_max: 0.0, host_max: 0.0, first_x: f64::NAN };
        for r in &recs {
            let got = f(r.x);
            rep.n += 1;
            let same = got.to_bits() == r.host.to_bits() || (got.is_nan() && r.host.is_nan());
            if same {
                rep.agree += 1;
            } else if rep.first_x.is_nan() {
                rep.first_x = r.x;
            }
            if let Some(e) = ulp_error(got, r) {
                if e.abs() > rep.rust_max {
                    rep.rust_max = e.abs();
                }
            }
            if let Some(e) = ulp_error(r.host, r) {
                if e.abs() > rep.host_max {
                    rep.host_max = e.abs();
                }
            }
        }
        Some(rep)
    }

    fn run(func: &str, f: fn(f64) -> f64, bit_exact_expected: bool, fails: &mut Vec<String>) {
        let mut any = false;
        for corpus in ["domain", "wide"] {
            let Some(rep) = measure(func, corpus, f) else { continue };
            any = true;
            let pct = 100.0 * rep.agree as f64 / rep.n as f64;
            eprintln!(
                "{func:>6} {corpus:<6} n={:<9} rust==host {:<9} ({pct:7.4}%)  \
                 max|err| rust {:.4} ulp, host {:.4} ulp",
                rep.n, rep.agree, rep.rust_max, rep.host_max
            );
            if bit_exact_expected {
                if rep.agree != rep.n {
                    fails.push(format!(
                        "{func}/{corpus}: {} of {} inputs disagree with the host libm \
                         (first {:e})",
                        rep.n - rep.agree,
                        rep.n,
                        rep.first_x
                    ));
                }
            } else {
                /* Correct rounding is the claim for these five: the error
                against the 113-bit reference must never exceed half an ulp
                by more than the double-double residual (~2^-48 ulp). */
                if rep.rust_max > 0.5 + 1e-9 {
                    fails.push(format!(
                        "{func}/{corpus}: not correctly rounded (max {:.6} ulp)",
                        rep.rust_max
                    ));
                }
            }
        }
        if !any {
            eprintln!("{func}: differential not run (no oracle; set SUNDIALS_LIBM_ORACLE_DIR)");
        }
    }

    #[test]
    fn libm_differential_arm_lineage() {
        /* glibc >= 2.28/2.29 ships this exact ARM optimized-routines source,
        so anything short of bit-identical is a translation defect. */
        let mut fails = Vec::new();
        run("exp", exp, true, &mut fails);
        run("log", log, true, &mut fails);
        assert!(fails.is_empty(), "{}", fails.join("\n"));
    }

    #[test]
    fn libm_differential_dd_derived() {
        /* glibc ships the SunPro fdlibm kernels for these, which measure
        0.79 to 1.75 ulp on this host. The pure-Rust versions are built on
        the double-double `exp_dd`/`log_dd` instead, so the claim checked
        here is correct rounding; the agreement percentage printed next to
        it is a measurement of how often glibc happens to agree. */
        let mut fails = Vec::new();
        run("expm1", expm1, false, &mut fails);
        run("log1p", log1p, false, &mut fails);
        run("sinh", sinh, false, &mut fails);
        run("cosh", cosh, false, &mut fails);
        run("acosh", acosh, false, &mut fails);
        assert!(fails.is_empty(), "{}", fails.join("\n"));
    }

    #[test]
    fn libm_differential_correctly_rounded() {
        /* glibc uses the LGPL IBM Accurate Mathematical Library here, which
        is ~0.51 ulp and cannot be copied into this tree. The claim made and
        checked instead is correct rounding; the agreement percentage printed
        alongside is a measurement, not a gate. */
        let mut fails = Vec::new();
        run("sin", sin, false, &mut fails);
        run("cos", cos, false, &mut fails);
        run("atan", atan, false, &mut fails);
        run("asin", asin, false, &mut fails);
        run("acos", acos, false, &mut fails);
        assert!(fails.is_empty(), "{}", fails.join("\n"));
    }
}
