#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]

/* -----------------------------------------------------------------
 * Ported from: examples/cvode/serial/cvDiurnal_kry_bp.c
 * -----------------------------------------------------------------
 * Example problem:
 *
 * An ODE system is generated from the following 2-species diurnal
 * kinetics advection-diffusion PDE system in 2 space dimensions.
 * The PDE system is treated by central differences on a uniform
 * 10 x 10 mesh, with simple polynomial initial profiles.
 * The problem is solved with CVODE, with the BDF/GMRES
 * method (i.e. using the SUNLinSol_SPGMR linear solver) and a banded
 * preconditioner, generated by difference quotients, using the
 * module CVBANDPRE. The problem is solved with left and right
 * preconditioning.
 * -----------------------------------------------------------------*/

use cvode_rs::prelude::*;

use std::any::Any;

/* helpful macros */

fn SQR(a: sunrealtype) -> sunrealtype {
    a * a
}

/* Problem Constants */

const ZERO: sunrealtype = 0.0;
const ONE: sunrealtype = 1.0;
const TWO: sunrealtype = 2.0;

const NUM_SPECIES: usize = 2; /* number of species         */
const KH: sunrealtype = 4.0e-6; /* horizontal diffusivity Kh */
const VEL: sunrealtype = 0.001; /* advection velocity V      */
const KV0: sunrealtype = 1.0e-8; /* coefficient in Kv(y)      */
const Q1: sunrealtype = 1.63e-16; /* coefficients q1, q2, c3   */
const Q2: sunrealtype = 4.66e-16;
const C3: sunrealtype = 3.7e16;
const A3: sunrealtype = 22.62; /* coefficient in expression for q3(t) */
const A4: sunrealtype = 7.601; /* coefficient in expression for q4(t) */
const C1_SCALE: sunrealtype = 1.0e6; /* coefficients in initial profiles    */
const C2_SCALE: sunrealtype = 1.0e12;

const T0: sunrealtype = ZERO; /* initial time */
const NOUT: i32 = 12; /* number of output times */
const TWOHR: sunrealtype = 7200.0; /* number of seconds in two hours  */
const HALFDAY: sunrealtype = 4.32e4; /* number of seconds in a half day */
const PI: sunrealtype = 3.1415926535898; /* pi */

const XMIN: sunrealtype = ZERO; /* grid boundaries in x  */
const XMAX: sunrealtype = 20.0;
const YMIN: sunrealtype = 30.0; /* grid boundaries in y  */
const YMAX: sunrealtype = 50.0;
const XMID: sunrealtype = 10.0; /* grid midpoints in x,y */
const YMID: sunrealtype = 40.0;

const MX: usize = 10; /* MX = number of x mesh points */
const MY: usize = 10; /* MY = number of y mesh points */
const NSMX: usize = 20; /* NSMX = NUM_SPECIES*MX */
const MM: usize = MX * MY; /* MM = MX*MY */

/* CVodeInit Constants */

const RTOL: sunrealtype = 1.0e-5; /* scalar relative tolerance */
const FLOOR: sunrealtype = 100.0; /* value of C1 or C2 at which tolerances */
/* change from relative to absolute      */
const ATOL: sunrealtype = RTOL * FLOOR; /* scalar absolute tolerance */
const NEQ: usize = NUM_SPECIES * MM; /* NEQ = number of equations */

/* User-defined vector accessor helper: IJKth.

IJKth(vdata,i,j,k) references the element in the vdata array for
species i at mesh point (j,k), where 1 <= i <= NUM_SPECIES,
0 <= j <= MX-1, 0 <= k <= MY-1. */

fn IJKth(i: usize, jx: usize, jy: usize) -> usize {
    i - 1 + jx * NUM_SPECIES + jy * NSMX
}

/* Type : UserData
contains problem constants */

struct UserData {
    q4: sunrealtype,
    om: sunrealtype,
    dx: sunrealtype,
    dy: sunrealtype,
    hdco: sunrealtype,
    haco: sunrealtype,
    vdco: sunrealtype,
}

/*
 *-------------------------------
 * Main Program
 *-------------------------------
 */

fn main() {
    /* Create the SUNDIALS context */
    let mut sunctx: Option<SUNContext> = None;
    let retval = SUNContext_Create(SUN_COMM_NULL, &mut sunctx);
    if check_retval(&retval, "SUNContext_Create") != 0 {
        std::process::exit(1);
    }
    let sunctx = sunctx.unwrap();

    /* Allocate and initialize u, and set problem data and tolerances */
    let u = N_VNew_Serial(NEQ as sunindextype, &sunctx);
    if check_ptr(&u, "N_VNew_Serial", 0) != 0 {
        std::process::exit(1);
    }
    let u = u.unwrap();
    let mut data = UserData {
        q4: ZERO,
        om: ZERO,
        dx: ZERO,
        dy: ZERO,
        hdco: ZERO,
        haco: ZERO,
        vdco: ZERO,
    };
    InitUserData(&mut data);
    /* keep copies of the mesh spacings before ownership of data moves
    into the solver memory (C keeps its own pointer to data) */
    let (dx, dy) = (data.dx, data.dy);
    SetInitialProfiles(&u, dx, dy);
    let abstol = ATOL;
    let reltol = RTOL;

    /* Call CVodeCreate to create the solver memory and specify the
     * Backward Differentiation Formula */
    let cvode_mem = CVodeCreate(CV_BDF, &sunctx);
    if check_ptr(&cvode_mem, "CVodeCreate", 0) != 0 {
        std::process::exit(1);
    }
    let cvode_mem = cvode_mem.unwrap();

    /* Set the pointer to user-defined data */
    let retval = CVodeSetUserData(&cvode_mem, Some(Box::new(data)));
    if check_retval(&retval, "CVodeSetUserData") != 0 {
        std::process::exit(1);
    }

    /* Call CVodeInit to initialize the integrator memory and specify the
     * user's right hand side function in u'=f(t,u), the initial time T0, and
     * the initial dependent variable vector u. */
    let retval = CVodeInit(&cvode_mem, f, T0, &u);
    if check_retval(&retval, "CVodeInit") != 0 {
        std::process::exit(1);
    }

    /* Call CVodeSStolerances to specify the scalar relative tolerance
     * and scalar absolute tolerances */
    let retval = CVodeSStolerances(&cvode_mem, reltol, abstol);
    if check_retval(&retval, "CVodeSStolerances") != 0 {
        std::process::exit(1);
    }

    /* Call SUNLinSol_SPGMR to specify the linear solver SPGMR
     * with left preconditioning and the default Krylov dimension */
    let LS = SUNLinSol_SPGMR(&u, SUN_PREC_LEFT, 0, &sunctx);
    if check_ptr(&LS, "SUNLinSol_SPGMR", 0) != 0 {
        std::process::exit(1);
    }
    let LS = LS.unwrap();

    /* Call CVodeSetLinearSolver to attach the linear solver to CVode */
    let retval = CVodeSetLinearSolver(&cvode_mem, &LS, None);
    if check_retval(&retval, "CVodeSetLinearSolver") != 0 {
        std::process::exit(1);
    }

    /* Call CVBandPreInit to initialize band preconditioner */
    let ml: sunindextype = 2;
    let mu: sunindextype = 2;
    let retval = CVBandPrecInit(&cvode_mem, NEQ as sunindextype, mu, ml);
    /* C checks this retval with opt == 0 (NULL-pointer check on &retval),
    which can never trigger; mirrored faithfully here */
    if check_ptr(&Some(retval), "CVBandPrecInit", 0) != 0 {
        std::process::exit(1);
    }

    PrintIntro(mu, ml);

    /* Loop over jpre (= SUN_PREC_LEFT, SUN_PREC_RIGHT), and solve the problem */

    for jpre in SUN_PREC_LEFT..=SUN_PREC_RIGHT {
        /* On second run, re-initialize u, the solver, and SPGMR */

        if jpre == SUN_PREC_RIGHT {
            SetInitialProfiles(&u, dx, dy);

            let retval = CVodeReInit(&cvode_mem, T0, &u);
            if check_retval(&retval, "CVodeReInit") != 0 {
                std::process::exit(1);
            }

            let retval = SUNLinSol_SPGMRSetPrecType(&LS, SUN_PREC_RIGHT);
            if check_retval(&retval, "SUNLinSol_SPGMRSetPrecType") != 0 {
                std::process::exit(1);
            }

            let retval = CVBandPrecInit(&cvode_mem, NEQ as sunindextype, mu, ml);
            if check_ptr(&Some(retval), "CVBandPrecInit", 0) != 0 {
                std::process::exit(1);
            }

            print!("\n\n-------------------------------------------------------");
            print!("------------\n");
        }

        print!(
            "\n\nPreconditioner type is:  jpre = {}\n\n",
            if jpre == SUN_PREC_LEFT {
                "SUN_PREC_LEFT"
            } else {
                "SUN_PREC_RIGHT"
            }
        );

        /* In loop over output points, call CVode, print results, test for error */

        let mut t: sunrealtype = 0.0;
        let mut tout = TWOHR;
        for _iout in 1..=NOUT {
            let retval = CVode(&cvode_mem, tout, &u, &mut t, CV_NORMAL);
            check_retval(&retval, "CVode");
            PrintOutput(&cvode_mem, &u, t);
            if retval != CV_SUCCESS {
                break;
            }
            tout += TWOHR;
        }

        /* Print final statistics */

        PrintFinalStats(&cvode_mem);
    } /* End of jpre loop */

    /* Free memory */
    N_VDestroy(u);
    let mut cvode_mem = Some(cvode_mem);
    CVodeFree(&mut cvode_mem); /* user data is dropped with the solver memory */
    SUNLinSolFree(Some(LS));
    let mut sunctx = Some(sunctx);
    SUNContext_Free(&mut sunctx);
}

/*
 *-------------------------------
 * Private helper functions
 *-------------------------------
 */

/* Load problem constants in data */

fn InitUserData(data: &mut UserData) {
    data.om = PI / HALFDAY;
    data.dx = (XMAX - XMIN) / ((MX - 1) as sunrealtype);
    data.dy = (YMAX - YMIN) / ((MY - 1) as sunrealtype);
    data.hdco = KH / SQR(data.dx);
    data.haco = VEL / (TWO * data.dx);
    data.vdco = (ONE / SQR(data.dy)) * KV0;
}

/* Set initial conditions in u */

fn SetInitialProfiles(u: &N_Vector, dx: sunrealtype, dy: sunrealtype) {
    /* Set pointer to data array in vector u. */

    let mut udata = N_VGetArrayPointer(u).expect("N_VGetArrayPointer");

    /* Load initial profiles of c1 and c2 into u vector */

    for jy in 0..MY {
        let y = YMIN + (jy as sunrealtype) * dy;
        let mut cy = SQR(0.1 * (y - YMID));
        cy = ONE - cy + 0.5 * SQR(cy);
        for jx in 0..MX {
            let x = XMIN + (jx as sunrealtype) * dx;
            let mut cx = SQR(0.1 * (x - XMID));
            cx = ONE - cx + 0.5 * SQR(cx);
            udata[IJKth(1, jx, jy)] = C1_SCALE * cx * cy;
            udata[IJKth(2, jx, jy)] = C2_SCALE * cx * cy;
        }
    }
}

fn PrintIntro(mu: sunindextype, ml: sunindextype) {
    print!(
        "2-species diurnal advection-diffusion problem, {} by {} mesh\n",
        MX, MY
    );
    print!(
        "SPGMR solver; band preconditioner; mu = {}, ml = {}\n\n",
        mu, ml
    );
}

/* Print current t, step count, order, stepsize, and sampled c1,c2 values */

fn PrintOutput(cvode_mem: &CVodeMem, u: &N_Vector, t: sunrealtype) {
    let mut nst: i64 = 0;
    let mut qu: i32 = 0;
    let mut hu: sunrealtype = ZERO;
    let (mxh, myh, mx1, my1) = (MX / 2 - 1, MY / 2 - 1, MX - 1, MY - 1);

    let retval = CVodeGetNumSteps(cvode_mem, &mut nst);
    check_retval(&retval, "CVodeGetNumSteps");
    let retval = CVodeGetLastOrder(cvode_mem, &mut qu);
    check_retval(&retval, "CVodeGetLastOrder");
    let retval = CVodeGetLastStep(cvode_mem, &mut hu);
    check_retval(&retval, "CVodeGetLastStep");

    let udata = N_VGetArrayPointer(u).expect("N_VGetArrayPointer");

    print!(
        "t = {}   no. steps = {}   order = {}   stepsize = {}\n",
        fmt_e(t, 2),
        nst,
        qu,
        fmt_e(hu, 2)
    );
    print!(
        "c1 (bot.left/middle/top rt.) = {}  {}  {}\n",
        fmt_ew(udata[IJKth(1, 0, 0)], 12, 3),
        fmt_ew(udata[IJKth(1, mxh, myh)], 12, 3),
        fmt_ew(udata[IJKth(1, mx1, my1)], 12, 3)
    );
    print!(
        "c2 (bot.left/middle/top rt.) = {}  {}  {}\n\n",
        fmt_ew(udata[IJKth(2, 0, 0)], 12, 3),
        fmt_ew(udata[IJKth(2, mxh, myh)], 12, 3),
        fmt_ew(udata[IJKth(2, mx1, my1)], 12, 3)
    );
}

/* Get and print final statistics */

fn PrintFinalStats(cvode_mem: &CVodeMem) {
    let (mut lenrw, mut leniw): (i64, i64) = (0, 0);
    let (mut lenrwLS, mut leniwLS): (i64, i64) = (0, 0);
    let (mut lenrwBP, mut leniwBP): (i64, i64) = (0, 0);
    let (mut nst, mut nfe, mut nsetups, mut nni, mut ncfn, mut netf): (
        i64,
        i64,
        i64,
        i64,
        i64,
        i64,
    ) = (0, 0, 0, 0, 0, 0);
    let (mut nli, mut npe, mut nps, mut ncfl, mut nfeLS): (i64, i64, i64, i64, i64) =
        (0, 0, 0, 0, 0);
    let mut nfeBP: i64 = 0;

    let retval = CVodeGetWorkSpace(cvode_mem, &mut lenrw, &mut leniw);
    check_retval(&retval, "CVodeGetWorkSpace");
    let retval = CVodeGetNumSteps(cvode_mem, &mut nst);
    check_retval(&retval, "CVodeGetNumSteps");
    let retval = CVodeGetNumRhsEvals(cvode_mem, &mut nfe);
    check_retval(&retval, "CVodeGetNumRhsEvals");
    let retval = CVodeGetNumLinSolvSetups(cvode_mem, &mut nsetups);
    check_retval(&retval, "CVodeGetNumLinSolvSetups");
    let retval = CVodeGetNumErrTestFails(cvode_mem, &mut netf);
    check_retval(&retval, "CVodeGetNumErrTestFails");
    let retval = CVodeGetNumNonlinSolvIters(cvode_mem, &mut nni);
    check_retval(&retval, "CVodeGetNumNonlinSolvIters");
    let retval = CVodeGetNumNonlinSolvConvFails(cvode_mem, &mut ncfn);
    check_retval(&retval, "CVodeGetNumNonlinSolvConvFails");

    let retval = CVodeGetLinWorkSpace(cvode_mem, &mut lenrwLS, &mut leniwLS);
    check_retval(&retval, "CVodeGetLinWorkSpace");
    let retval = CVodeGetNumLinIters(cvode_mem, &mut nli);
    check_retval(&retval, "CVodeGetNumLinIters");
    let retval = CVodeGetNumPrecEvals(cvode_mem, &mut npe);
    check_retval(&retval, "CVodeGetNumPrecEvals");
    let retval = CVodeGetNumPrecSolves(cvode_mem, &mut nps);
    check_retval(&retval, "CVodeGetNumPrecSolves");
    let retval = CVodeGetNumLinConvFails(cvode_mem, &mut ncfl);
    check_retval(&retval, "CVodeGetNumLinConvFails");
    let retval = CVodeGetNumLinRhsEvals(cvode_mem, &mut nfeLS);
    check_retval(&retval, "CVodeGetNumLinRhsEvals");

    let retval = CVBandPrecGetWorkSpace(cvode_mem, &mut lenrwBP, &mut leniwBP);
    check_retval(&retval, "CVBandPrecGetWorkSpace");
    let retval = CVBandPrecGetNumRhsEvals(cvode_mem, &mut nfeBP);
    check_retval(&retval, "CVBandPrecGetNumRhsEvals");

    print!("\nFinal Statistics.. \n\n");
    print!("lenrw   = {:5}     leniw   = {:5}\n", lenrw, leniw);
    print!("lenrwls = {:5}     leniwls = {:5}\n", lenrwLS, leniwLS);
    print!("lenrwbp = {:5}     leniwbp = {:5}\n", lenrwBP, leniwBP);
    print!("nst     = {:5}\n", nst);
    print!(
        "nfe     = {:5}     nfetot  = {:5}\n",
        nfe,
        nfe + nfeLS + nfeBP
    );
    print!("nfeLS   = {:5}     nfeBP   = {:5}\n", nfeLS, nfeBP);
    print!("nni     = {:5}     nli     = {:5}\n", nni, nli);
    print!("nsetups = {:5}     netf    = {:5}\n", nsetups, netf);
    print!("npe     = {:5}     nps     = {:5}\n", npe, nps);
    print!("ncfn    = {:5}     ncfl    = {:5}\n\n", ncfn, ncfl);
}

/* Check function return value...
check_retval: SUNDIALS function returns an integer value so check if
              retval < 0 (C check_retval with opt == 1)
check_ptr:    function allocates memory so check if returned
              NULL pointer (C check_retval with opt == 0 or opt == 2) */

fn check_retval(retval: &i32, funcname: &str) -> i32 {
    if *retval < 0 {
        eprint!(
            "\nSUNDIALS_ERROR: {}() failed with retval = {}\n\n",
            funcname, retval
        );
        return 1;
    }
    0
}

fn check_ptr<T>(returnvalue: &Option<T>, funcname: &str, opt: i32) -> i32 {
    if returnvalue.is_none() {
        if opt == 0 {
            eprint!(
                "\nSUNDIALS_ERROR: {}() failed - returned NULL pointer\n\n",
                funcname
            );
        } else {
            eprint!(
                "\nMEMORY_ERROR: {}() failed - returned NULL pointer\n\n",
                funcname
            );
        }
        return 1;
    }
    0
}

/*
 *-------------------------------
 * Function called by the solver
 *-------------------------------
 */

/* f routine. Compute RHS function f(t,u). */

fn f(t: sunrealtype, u: &N_Vector, udot: &N_Vector, user_data: &mut Option<Box<dyn Any>>) -> i32 {
    let data = user_data
        .as_mut()
        .and_then(|b| b.downcast_mut::<UserData>())
        .expect("user_data is UserData");
    let udata = N_VGetArrayPointer(u).expect("N_VGetArrayPointer");
    let mut dudata = N_VGetArrayPointer(udot).expect("N_VGetArrayPointer");

    /* Set diurnal rate coefficients. */

    let s = (data.om * t).sun_sin();
    let q3;
    if s > ZERO {
        q3 = (-A3 / s).sun_exp();
        data.q4 = (-A4 / s).sun_exp();
    } else {
        q3 = ZERO;
        data.q4 = ZERO;
    }

    /* Make local copies of problem variables, for efficiency. */

    let q4coef = data.q4;
    let dely = data.dy;
    let verdco = data.vdco;
    let hordco = data.hdco;
    let horaco = data.haco;

    /* Loop over all grid points. */

    for jy in 0..MY {
        /* Set vertical diffusion coefficients at jy +- 1/2 */

        let ydn = YMIN + (jy as sunrealtype - 0.5) * dely;
        let yup = ydn + dely;
        let cydn = verdco * (0.2 * ydn).sun_exp();
        let cyup = verdco * (0.2 * yup).sun_exp();
        let idn: i32 = if jy == 0 { 1 } else { -1 };
        let iup: i32 = if jy == MY - 1 { -1 } else { 1 };
        for jx in 0..MX {
            /* Extract c1 and c2, and set kinetic rate terms. */

            let c1 = udata[IJKth(1, jx, jy)];
            let c2 = udata[IJKth(2, jx, jy)];
            let qq1 = Q1 * c1 * C3;
            let qq2 = Q2 * c1 * c2;
            let qq3 = q3 * C3;
            let qq4 = q4coef * c2;
            let rkin1 = -qq1 - qq2 + TWO * qq3 + qq4;
            let rkin2 = qq1 - qq2 - qq4;

            /* Set vertical diffusion terms. */

            let c1dn = udata[IJKth(1, jx, (jy as i32 + idn) as usize)];
            let c2dn = udata[IJKth(2, jx, (jy as i32 + idn) as usize)];
            let c1up = udata[IJKth(1, jx, (jy as i32 + iup) as usize)];
            let c2up = udata[IJKth(2, jx, (jy as i32 + iup) as usize)];
            let vertd1 = cyup * (c1up - c1) - cydn * (c1 - c1dn);
            let vertd2 = cyup * (c2up - c2) - cydn * (c2 - c2dn);

            /* Set horizontal diffusion and advection terms. */

            let ileft: i32 = if jx == 0 { 1 } else { -1 };
            let iright: i32 = if jx == MX - 1 { -1 } else { 1 };
            let c1lt = udata[IJKth(1, (jx as i32 + ileft) as usize, jy)];
            let c2lt = udata[IJKth(2, (jx as i32 + ileft) as usize, jy)];
            let c1rt = udata[IJKth(1, (jx as i32 + iright) as usize, jy)];
            let c2rt = udata[IJKth(2, (jx as i32 + iright) as usize, jy)];
            let hord1 = hordco * (c1rt - TWO * c1 + c1lt);
            let hord2 = hordco * (c2rt - TWO * c2 + c2lt);
            let horad1 = horaco * (c1rt - c1lt);
            let horad2 = horaco * (c2rt - c2lt);

            /* Load all terms into udot. */

            dudata[IJKth(1, jx, jy)] = vertd1 + hord1 + horad1 + rkin1;
            dudata[IJKth(2, jx, jy)] = vertd2 + hord2 + horad2 + rkin2;
        }
    }

    0
}
