#!/usr/bin/env python3
"""Phase-7 verifier: compile every Tier-B Rust snippet.

Emits one scratch example into posim/examples/ (posim depends on all four
Tier-B crates), wraps each snippet in its own function, and builds it. A
snippet that fails to compile has its `verified` cleared, so it is badged
unverified in the app rather than presented as working.

The scratch file is removed afterwards whether the build succeeds or not:
it must never be left in the tree to be committed or to break
`cargo build --workspace`.

Usage: python3 tools/verify_tierb_examples.py [--keep]
"""

import datetime
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "posim", "examples", "_tierb_compile_check.rs")
ENTRIES = os.path.join(ROOT, "index_data", "entries_tierb.json")
# The day this actually ran. Hardcoding it is how the per-example
# dates drifted away from the catalog's own verified_date: a stamp
# that does not move is a stamp that stops being true.
TODAY = datetime.date.today().isoformat()


def build_file(entries):
    parts = ["// GENERATED by tools/verify_tierb_examples.py — do not commit.",
             "#![allow(unused, non_snake_case, non_camel_case_types)]", ""]
    index = []
    for i, e in enumerate(entries):
        for j, x in enumerate(e["examples"]):
            if x["medium"] != "rust":
                continue
            body = x["code"]
            uses = [l for l in body.splitlines() if l.startswith("use ")]
            rest = [l for l in body.splitlines() if not l.startswith("use ")]
            fname = "chk_%d_%d" % (i, j)
            parts.append("#[allow(dead_code)]")
            parts.append("fn %s() -> Result<(), String> {" % fname)
            parts += ["    " + u for u in uses]
            parts += ["    " + l for l in rest if l.strip()]
            parts.append("    Ok(())")
            parts.append("}")
            parts.append("")
            index.append((fname, i, j, e["id"]))
    parts.append("fn main() { println!(\"tier-b compile check\"); }")
    return "\n".join(parts), index


def main():
    keep = "--keep" in sys.argv
    entries = json.load(open(ENTRIES))
    src, index = build_file(entries)
    os.makedirs(os.path.dirname(SRC), exist_ok=True)
    open(SRC, "w").write(src)
    print("wrote %d snippets into %s" % (len(index), SRC))
    try:
        r = subprocess.run(
            ["cargo", "build", "-p", "posim", "--example", "_tierb_compile_check",
             "--message-format=short"],
            capture_output=True, text=True, cwd=ROOT, timeout=1800)
    except subprocess.TimeoutExpired:
        sys.exit("cargo build timed out after 1800 s — nothing was marked verified")
    finally:
        if not keep and os.path.exists(SRC):
            os.remove(SRC)

    lines = src.split("\n")
    fn_start = {}
    for fname, i, j, eid in index:
        for n, l in enumerate(lines, 1):
            if l.startswith("fn %s(" % fname):
                fn_start[n] = (fname, i, j, eid)
                break

    starts = sorted(fn_start)
    def owner(lineno):
        prev = None
        for s in starts:
            if s <= lineno:
                prev = s
            else:
                break
        return fn_start.get(prev)

    bad = {}
    for m in re.finditer(r"^posim/examples/_tierb_compile_check\.rs:(\d+):\d+: error(.*)$",
                         r.stderr, re.M):
        o = owner(int(m.group(1)))
        if o:
            bad.setdefault(o[3], []).append(m.group(2).strip()[:130])

    # A build failure that maps to no snippet must FAIL the run, not
    # stamp every snippet verified — the vacuous-gate failure mode
    # certify_clean.sh and mutation_probe.sh were written to hunt down.
    if r.returncode != 0 and not bad:
        sys.exit("cargo build FAILED but no error mapped to any snippet — "
                 "refusing to mark anything verified:\n" + r.stderr[-2000:])

    ok = 0
    for e in entries:
        for x in e["examples"]:
            if x["medium"] != "rust":
                continue
            if e["id"] in bad:
                x["expected"], x["verified"] = None, None
                e["status"] = "stub"
            else:
                x["expected"] = "compiles"
                x["verified"] = TODAY
                ok += 1
    json.dump(entries, open(ENTRIES, "w"), indent=1)

    total = len(index)
    print("\nCOMPILED %d/%d  (%.1f%%)" % (ok, total, 100.0 * ok / total if total else 0))
    if bad:
        print("\n%d entry(ies) failed:" % len(bad))
        for eid, errs in list(bad.items())[:25]:
            print("  %s\n      %s" % (eid, errs[0]))
        if len(bad) > 25:
            print("  ... and %d more" % (len(bad) - 25))
    return 0


if __name__ == "__main__":
    sys.exit(main())
