//! Matrix-free symmetric eigensolver by the Lanczos algorithm.
//!
//! [`crate::eigen::jacobi_eigen`] needs the matrix written out, and
//! costs `O(n^3)`. That is fine to a few hundred rows and hopeless
//! beyond: a 2-D quantum grid of 200 x 200 points has a Hamiltonian of
//! 40 000 x 40 000, which is 12 GB dense before any arithmetic happens.
//!
//! Lanczos never forms the matrix. It needs only the action `v -> A v`,
//! which for a finite-difference Hamiltonian is a five-point stencil
//! costing `O(n)`. It builds a Krylov basis, projects `A` onto it as a
//! small tridiagonal `T`, and the eigenvalues of `T` (the *Ritz values*)
//! converge to the extremal eigenvalues of `A` — fastest at the two
//! ends of the spectrum, which is exactly where bound states live.
//!
//! # Two separate degeneracy problems
//!
//! Getting repeated eigenvalues right needs **two** mechanisms, and
//! conflating them is easy — an earlier version of this module did, and
//! its documentation claimed one of them solved both.
//!
//! **Ghosts.** In exact arithmetic the Lanczos vectors are orthogonal;
//! in floating point they lose orthogonality as soon as a Ritz value
//! converges, and the algorithm rediscovers eigenvalues it has already
//! found. These spurious copies look exactly like genuine degeneracy.
//! The cure is **full reorthogonalisation**: every new vector is
//! reorthogonalised against all previous ones, at `O(m^2 n)` instead of
//! `O(m n)`.
//!
//! **Genuine multiplicity.** Full reorthogonalisation does *not* help
//! here, and this is the part that is easy to get wrong. A Krylov space
//! built from a single starting vector contains exactly **one**
//! direction out of each degenerate eigenspace, so plain Lanczos finds
//! each distinct eigenvalue once however long it runs. It is not a
//! precision problem and no tolerance fixes it.
//!
//! That matters because the systems this exists for genuinely are
//! degenerate: the 2-D isotropic oscillator has `E = 2` twice and
//! `E = 3` three times. So the wanted pairs are extracted one at a time
//! by **deflation** — each converged eigenvector is shifted to the top
//! of the spectrum by adding `sigma |x><x|`, and the solver is re-run.
//! The next run then finds the orthogonal partner inside the same
//! eigenspace, because the direction already found is no longer at the
//! bottom.
//!
//! Deflating by *shifting* rather than projecting matters: projection
//! would leave a zero eigenvalue on the found subspace, and for a
//! positive spectrum zero is below everything, so the solver would
//! return the deflated directions again as spurious ground states.
//!
//! # Reproducibility
//!
//! The starting vector is generated by a fixed-seed integer generator,
//! never a clock or an OS source, so the same problem gives bit-identical
//! answers on every run and every machine.

use crate::eigen::jacobi_eigen;

/// How the iteration was stopped.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Stop {
    /// Every wanted Ritz pair met the residual tolerance.
    Converged,
    /// The Krylov space was exhausted (`m` reached `n`), which is exact.
    Exhausted,
    /// `max_iters` was reached first — results are returned anyway, with
    /// their residuals, so the caller can judge.
    MaxIters,
}

/// The outcome of a Lanczos run.
#[derive(Clone, Debug)]
pub struct LanczosResult {
    /// The `k` lowest eigenvalues, ascending.
    pub values: Vec<f64>,
    /// The corresponding eigenvectors, each of length `n`.
    pub vectors: Vec<Vec<f64>>,
    /// `‖A x - theta x‖` for each pair — the honest accuracy statement.
    pub residuals: Vec<f64>,
    /// Krylov dimension actually used.
    pub iterations: usize,
    pub stop: Stop,
}

/// A tiny fixed-seed generator, so a run is reproducible.
///
/// This is a starting vector for a Krylov method, not cryptography: all
/// it must do is have a component along every eigenvector, and do so
/// identically on every machine.
/// Each deflation pass needs a DIFFERENT start, which is why the seed
/// is a parameter. The start vector's projection onto a degenerate
/// eigenspace is a single direction; if the next pass reuses it, that
/// direction is exactly the one just deflated and the partner has zero
/// component — unreachable however long the run. Varying the seed gives
/// a generically different direction in the same eigenspace.
fn seeded_start(n: usize, seed: u64) -> Vec<f64> {
    let mut s: u64 = 0x2545_F491_4F6C_DD1D ^ seed.wrapping_mul(0x9E37_79B9_7F4A_7C15);
    if s == 0 {
        s = 0x1234_5678_9ABC_DEF1;
    }
    (0..n)
        .map(|_| {
            s ^= s << 13;
            s ^= s >> 7;
            s ^= s << 17;
            // map to (-1, 1)
            (s >> 11) as f64 / (1u64 << 52) as f64 * 2.0 - 1.0
        })
        .collect()
}

fn dot(a: &[f64], b: &[f64]) -> f64 {
    a.iter().zip(b).map(|(x, y)| x * y).sum()
}

fn axpy(y: &mut [f64], a: f64, x: &[f64]) {
    for (yi, xi) in y.iter_mut().zip(x) {
        *yi += a * xi;
    }
}

fn scale(v: &mut [f64], a: f64) {
    for x in v.iter_mut() {
        *x *= a;
    }
}

/// The `k` lowest eigenpairs of a symmetric operator, matrix-free.
///
/// `apply` must compute `A v` for a vector of length `n` and must be
/// **symmetric** — this is not checked, because checking would need the
/// matrix. Feeding it a non-symmetric operator produces meaningless
/// numbers rather than an error.
///
/// `tol` is the residual `‖A x - theta x‖` each pair must reach.
///
/// # Errors
/// `k == 0`, `k > n`, `n == 0`, or a non-finite value returned by
/// `apply` (which is reported rather than propagated as NaN).
///
/// # Examples
/// ```
/// use special_functions::lanczos::lanczos_lowest;
/// // A diagonal operator: eigenvalues are just the diagonal entries.
/// let d: Vec<f64> = (0..50).map(|i| 10.0 - i as f64 * 0.1).collect();
/// let dd = d.clone();
/// let r = lanczos_lowest(50, 3, |v| v.iter().zip(&dd).map(|(x, a)| x * a).collect(), 1e-9, 300)
///     .unwrap();
/// // lowest three of 10.0 - 0.1 i are at i = 49, 48, 47
/// assert!((r.values[0] - 5.1).abs() < 1e-8);
/// assert!((r.values[1] - 5.2).abs() < 1e-8);
/// ```
pub fn lanczos_lowest<F>(
    n: usize,
    k: usize,
    apply: F,
    tol: f64,
    max_iters: usize,
) -> Result<LanczosResult, String>
where
    F: Fn(&[f64]) -> Vec<f64>,
{
    if n == 0 {
        return Err("lanczos: the operator has dimension 0".to_string());
    }
    if k == 0 {
        return Err("lanczos: ask for at least one eigenpair".to_string());
    }
    if k > n {
        return Err(format!("lanczos: asked for {k} eigenpairs of a {n}-dimensional operator"));
    }

    let mut values = Vec::with_capacity(k);
    let mut vectors: Vec<Vec<f64>> = Vec::with_capacity(k);
    let mut residuals = Vec::with_capacity(k);
    let mut iterations = 0usize;
    let mut stop = Stop::Converged;
    // Set from the first run's Ritz spectrum: high enough that a
    // deflated direction lands above everything we care about.
    let mut sigma = 0.0_f64;

    for want in 0..k {
        let found = vectors.clone();
        let sg = sigma;
        let deflated = |v: &[f64]| -> Vec<f64> {
            let mut w = apply(v);
            for x in &found {
                let c = dot(x, v) * sg;
                axpy(&mut w, c, x);
            }
            w
        };
        let r = lanczos_core(n, 1, deflated, tol, max_iters, want as u64)?;
        if want == 0 {
            // Spread of the Ritz spectrum bounds the whole spectrum well
            // enough to push deflated directions clear of the bottom.
            sigma = (r.spectrum_max - r.values[0]).abs() * 2.0 + 10.0;
        }
        values.push(r.values[0]);
        vectors.push(r.vectors[0].clone());
        residuals.push(r.residuals[0]);
        iterations += r.iterations;
        if r.stop == Stop::MaxIters {
            stop = Stop::MaxIters;
        } else if r.stop == Stop::Exhausted && stop == Stop::Converged {
            stop = Stop::Exhausted;
        }
    }
    Ok(LanczosResult { values, vectors, residuals, iterations, stop })
}

/// One Lanczos run: the `k` lowest Ritz pairs of `apply`, with no
/// deflation. Finds each DISTINCT eigenvalue once; see the module note.
fn lanczos_core<F>(
    n: usize,
    k: usize,
    apply: F,
    tol: f64,
    max_iters: usize,
    seed: u64,
) -> Result<CoreResult, String>
where
    F: Fn(&[f64]) -> Vec<f64>,
{
    if n == 0 {
        return Err("lanczos: the operator has dimension 0".to_string());
    }
    if k == 0 {
        return Err("lanczos: ask for at least one eigenpair".to_string());
    }
    if k > n {
        return Err(format!("lanczos: asked for {k} eigenpairs of a {n}-dimensional operator"));
    }

    // The Krylov space cannot exceed n, and needs headroom above k for
    // the wanted end of the spectrum to separate.
    let m_max = max_iters.min(n).max(k.min(n));

    let mut v: Vec<Vec<f64>> = Vec::with_capacity(m_max);
    let mut alpha: Vec<f64> = Vec::with_capacity(m_max);
    let mut beta: Vec<f64> = Vec::with_capacity(m_max);

    let mut q = seeded_start(n, seed);
    let nrm = dot(&q, &q).sqrt();
    if nrm == 0.0 {
        return Err("lanczos: the starting vector vanished".to_string());
    }
    scale(&mut q, 1.0 / nrm);
    v.push(q);

    let mut stop = Stop::MaxIters;
    let mut used = 0usize;
    // The beta that WOULD extend the basis, carried out of the loop so
    // the final residual is real. Setting it to 0 unconditionally (as an
    // earlier version did) reported "residual 0.00e0" next to "NOT
    // converged" — a self-contradiction, and the zero was the lie.
    let mut last_b = 0.0_f64;

    for j in 0..m_max {
        let mut w = apply(&v[j]);
        if w.len() != n {
            return Err(format!(
                "lanczos: apply returned {} values for a {n}-dimensional vector",
                w.len()
            ));
        }
        if let Some(i) = w.iter().position(|x| !x.is_finite()) {
            return Err(format!("lanczos: apply produced a non-finite value at index {i}"));
        }
        let a = dot(&w, &v[j]);
        alpha.push(a);
        axpy(&mut w, -a, &v[j]);
        if j > 0 {
            let b = beta[j - 1];
            let prev = v[j - 1].clone();
            axpy(&mut w, -b, &prev);
        }

        // FULL reorthogonalisation — twice, because one pass is not
        // always enough when cancellation is severe (the classical
        // "twice is enough" result).
        for _ in 0..2 {
            for vi in v.iter() {
                let c = dot(&w, vi);
                axpy(&mut w, -c, vi);
            }
        }

        used = j + 1;
        let b = dot(&w, &w).sqrt();

        // Check convergence on the projected problem.
        if used >= k && (used.is_multiple_of(5) || used == m_max || b <= 1e-14) {
            // `b` is the beta that WOULD extend the basis; it is the one
            // the residual bound needs, and it has not been pushed yet.
            if let Some(res) = try_extract(&alpha, &beta, &v, k, n, b)? {
                if res.residuals.iter().all(|r| *r <= tol) {
                    return Ok(CoreResult { stop: Stop::Converged, iterations: used, ..res });
                }
            }
        }

        if b <= 1e-14 {
            // The Krylov space genuinely closed: the residual IS zero.
            stop = Stop::Exhausted;
            last_b = 0.0;
            break;
        }
        last_b = b;
        if used == m_max {
            break;
        }
        beta.push(b);
        let mut nq = w;
        scale(&mut nq, 1.0 / b);
        v.push(nq);
    }

    let res = try_extract(&alpha, &beta, &v, k, n, last_b)?
        .ok_or_else(|| "lanczos: the projected problem could not be solved".to_string())?;
    Ok(CoreResult { stop, iterations: used, ..res })
}

/// One run's output, plus the top of the Ritz spectrum, which the
/// deflation shift needs.
#[derive(Clone, Debug)]
struct CoreResult {
    values: Vec<f64>,
    vectors: Vec<Vec<f64>>,
    residuals: Vec<f64>,
    iterations: usize,
    stop: Stop,
    spectrum_max: f64,
}

/// Diagonalise the projected tridiagonal `T` and lift the wanted Ritz
/// pairs back to the full space.
fn try_extract(
    alpha: &[f64],
    beta: &[f64],
    v: &[Vec<f64>],
    k: usize,
    n: usize,
    b_next: f64,
) -> Result<Option<CoreResult>, String> {
    let m = alpha.len();
    if m < k {
        return Ok(None);
    }
    // Build T densely: m is the Krylov dimension, small by construction,
    // so an O(m^3) Jacobi sweep here is cheap next to the O(m^2 n)
    // reorthogonalisation.
    let mut t = vec![vec![0.0; m]; m];
    for i in 0..m {
        t[i][i] = alpha[i];
        if i + 1 < m {
            let b = beta[i];
            t[i][i + 1] = b;
            t[i + 1][i] = b;
        }
    }
    let (vals, vecs) = jacobi_eigen(&t)?;

    let mut values = Vec::with_capacity(k);
    let mut vectors = Vec::with_capacity(k);
    let mut residuals = Vec::with_capacity(k);
    for j in 0..k {
        values.push(vals[j]);
        // Ritz vector x = sum_i y_i v_i
        let y = &vecs[j];
        let mut x = vec![0.0; n];
        for (i, vi) in v.iter().enumerate().take(m) {
            axpy(&mut x, y[i], vi);
        }
        // renormalise: rounding in the lift can drift the length
        let s = dot(&x, &x).sqrt();
        if s > 0.0 {
            scale(&mut x, 1.0 / s);
        }
        // The standard Lanczos residual bound,
        //     ‖A x_i - theta_i x_i‖ = |beta_next| * |y_{m,i}|,
        // using the beta that would extend the basis. An earlier version
        // indexed `beta[m-1]`, which does not exist while alpha has m
        // entries and beta has m-1 — so every residual came out 0.0, the
        // convergence test passed on the first check, and the solver
        // returned garbage after k iterations. A residual that cannot be
        // non-zero is not a residual.
        let r = b_next.abs() * y[m - 1].abs();
        residuals.push(r);
        vectors.push(x);
    }
    Ok(Some(CoreResult {
        values,
        vectors,
        residuals,
        iterations: m,
        stop: Stop::MaxIters,
        spectrum_max: *vals.last().unwrap_or(&0.0),
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::eigen::eigenvalues;

    /// A diagonal operator has its diagonal as spectrum — the simplest
    /// possible check that the lowest end is found.
    #[test]
    fn diagonal_operator() {
        let n = 200;
        let d: Vec<f64> = (0..n).map(|i| (i as f64 - 40.0).abs()).collect();
        let dd = d.clone();
        let r = lanczos_lowest(n, 4, |v| v.iter().zip(&dd).map(|(x, a)| x * a).collect(), 1e-10, 400)
            .unwrap();
        let mut sorted = d.clone();
        sorted.sort_by(|a, b| a.partial_cmp(b).unwrap());
        for (j, (got, want)) in r.values.iter().zip(&sorted).take(4).enumerate() {
            assert!((got - want).abs() < 1e-8, "value {j}: {got} vs {want}");
        }
    }

    /// Cross-check against the dense Jacobi solver on a matrix small
    /// enough for both. Two unrelated algorithms agreeing is the real
    /// evidence.
    // Building a symmetric matrix by index is clearer than any iterator
    // form, and the mirror assignment needs both indices at once.
    #[allow(clippy::needless_range_loop)]
    #[test]
    fn agrees_with_the_dense_solver() {
        let n = 120;
        // a symmetric matrix with structure but no special form
        let mut a = vec![vec![0.0; n]; n];
        for i in 0..n {
            for j in 0..n {
                if i <= j {
                    let v = ((i * 7 + j * 13) % 11) as f64 * 0.1
                        + if i == j { 2.0 * (i as f64).sqrt() } else { 0.0 };
                    a[i][j] = v;
                    a[j][i] = v;
                }
            }
        }
        let dense = eigenvalues(&a).unwrap();
        let aa = a.clone();
        let r = lanczos_lowest(
            n,
            5,
            |v| {
                (0..n)
                    .map(|i| aa[i].iter().zip(v).map(|(x, y)| x * y).sum())
                    .collect()
            },
            1e-10,
            400,
        )
        .unwrap();
        for (j, (got, want)) in r.values.iter().zip(&dense).take(5).enumerate() {
            assert!((got - want).abs() < 1e-7, "eigenvalue {j}: lanczos {got} vs jacobi {want}");
        }
    }

    /// **Genuine degeneracies must survive, and false ones must not
    /// appear.** This is what full reorthogonalisation buys: a naive
    /// Lanczos would report extra copies of converged eigenvalues
    /// (ghosts) that are indistinguishable from real degeneracy.
    #[test]
    fn real_degeneracies_are_found_and_ghosts_are_not_invented() {
        // Spectrum: 1 once, 2 twice, 3 three times, then 10, 11, ...
        let mut d = vec![1.0, 2.0, 2.0, 3.0, 3.0, 3.0];
        d.extend((0..194).map(|i| 10.0 + i as f64));
        let n = d.len();
        let dd = d.clone();
        let r = lanczos_lowest(n, 6, |v| v.iter().zip(&dd).map(|(x, a)| x * a).collect(), 1e-10, 400)
            .unwrap();
        let want = [1.0, 2.0, 2.0, 3.0, 3.0, 3.0];
        for (j, (got, w)) in r.values.iter().zip(&want).enumerate() {
            assert!((got - w).abs() < 1e-7, "value {j}: {got} vs {w}");
        }
        // and the eigenvectors of a degenerate pair must be orthogonal,
        // not two copies of the same direction — the giveaway for ghosts
        let ip = dot(&r.vectors[1], &r.vectors[2]).abs();
        assert!(ip < 1e-6, "degenerate eigenvectors are not orthogonal: <1|2> = {ip}");
        let ip = dot(&r.vectors[3], &r.vectors[4]).abs();
        assert!(ip < 1e-6, "degenerate eigenvectors are not orthogonal: <3|4> = {ip}");
    }

    /// All returned eigenvectors must be orthonormal.
    #[test]
    fn eigenvectors_are_orthonormal() {
        let n = 150;
        let d: Vec<f64> = (0..n).map(|i| ((i * 37) % 53) as f64 + i as f64 * 0.01).collect();
        let dd = d.clone();
        let r = lanczos_lowest(n, 5, |v| v.iter().zip(&dd).map(|(x, a)| x * a).collect(), 1e-10, 400)
            .unwrap();
        for i in 0..5 {
            for j in 0..5 {
                let ip = dot(&r.vectors[i], &r.vectors[j]);
                let want = if i == j { 1.0 } else { 0.0 };
                assert!((ip - want).abs() < 1e-7, "<{i}|{j}> = {ip}, want {want}");
            }
        }
    }

    /// The residual really is `‖A x - theta x‖`: verified explicitly
    /// against the cheap `beta * y_m` bound the solver reports.
    #[test]
    fn reported_residuals_match_the_true_ones() {
        let n = 180;
        let d: Vec<f64> = (0..n).map(|i| (i as f64 * 0.37).sin() * 5.0 + 6.0).collect();
        let dd = d.clone();
        let op = |v: &[f64]| -> Vec<f64> { v.iter().zip(&dd).map(|(x, a)| x * a).collect() };
        let r = lanczos_lowest(n, 3, op, 1e-10, 400).unwrap();
        for (j, x) in r.vectors.iter().enumerate().take(3) {
            let ax = op(x);
            let true_res: f64 = ax
                .iter()
                .zip(x)
                .map(|(a, xi)| (a - r.values[j] * xi).powi(2))
                .sum::<f64>()
                .sqrt();
            assert!(
                true_res < 1e-6,
                "pair {j}: true residual {true_res}, reported {}",
                r.residuals[j]
            );
        }
    }

    /// The starting vector is seeded deterministically, so two runs of
    /// the same problem must agree bit for bit.
    #[test]
    fn results_are_reproducible() {
        let n = 100;
        let d: Vec<f64> = (0..n).map(|i| i as f64).collect();
        let go = || {
            let dd = d.clone();
            lanczos_lowest(n, 3, move |v| v.iter().zip(&dd).map(|(x, a)| x * a).collect(), 1e-10, 200)
                .unwrap()
        };
        let a = go();
        let b = go();
        assert_eq!(a.values, b.values, "eigenvalues differed between runs");
        assert_eq!(a.vectors, b.vectors, "eigenvectors differed between runs");
    }

    #[test]
    fn invalid_input_is_reported() {
        let op = |v: &[f64]| v.to_vec();
        assert!(lanczos_lowest(0, 1, op, 1e-9, 10).is_err(), "n = 0");
        assert!(lanczos_lowest(10, 0, op, 1e-9, 10).is_err(), "k = 0");
        assert!(lanczos_lowest(10, 11, op, 1e-9, 10).is_err(), "k > n");
        // an operator returning the wrong length
        assert!(
            lanczos_lowest(10, 1, |_| vec![0.0; 3], 1e-9, 10).is_err(),
            "wrong output length"
        );
        // an operator returning NaN
        assert!(
            lanczos_lowest(10, 1, |_| vec![f64::NAN; 10], 1e-9, 10).is_err(),
            "non-finite output"
        );
    }
}
